/* Shared i18n for Study Sprint legal & support pages. Language persists via localStorage (sst_lang). */
(function () {
  var I18N = {
    en: {
      nav_home:`Home`,
      nav_privacy:`Privacy`,
      nav_terms:`Terms`,
      nav_support:`Support`,
      nav_help:`Get Help`,
      nav_contact:`Contact`,
      sup_hero_title:`Support & Help Center`,
      sup_hero_sub:`We're here to help you focus.`,
      sup_get_title:`Get in touch`,
      sup_get_desc:`Need help, found a bug, or have a feature idea? We'd love to hear from you.`,
      sup_get_btn:`Contact Support`,
      sup_or_pre:`Or email us directly at`,
      sup_or_post:`. We typically reply within a few days.`,
      sup_faq_title:`Frequently Asked Questions`,
      sup_q1:`Does the app work offline?`,
      sup_a1:`Yes. Study Sprint Timer is offline-first — no account or internet connection is required to run study sessions and track your progress.`,
      sup_q2:`How do streaks work?`,
      sup_a2:`Complete at least one study session on a given day to keep your streak going. Miss a day and the streak resets — a gentle nudge to stay consistent.`,
      sup_q3:`How do I change the theme?`,
      sup_a3:`Open Settings → Theme and pick any color you like. On supported devices, the home-screen app icon updates to match your selected theme.`,
      sup_q4:`How do I remove ads?`,
      sup_a4:`Upgrade to Premium from the app to enjoy an ad-free experience and unlock extra themes.`,
      sup_q5:`How do I restore my purchase?`,
      sup_a5:`Go to Settings → Restore Purchases. Make sure you're signed in with the same Apple ID you used for the original purchase.`,
      sup_q6:`How do I delete my data?`,
      sup_a6:`All data is stored locally. You can clear everything from Settings → Clear Data, or by uninstalling the app.`,
      sup_q7:`Is there an Apple Watch app?`,
      sup_a7:`Yes. Install the Watch app to start sprints from your wrist; sessions sync back to your iPhone automatically.`,
      sup_q8:`Can I save sessions to Apple Health?`,
      sup_a8:`Yes. Turn on "Write to Apple Health" in Settings; completed sessions appear in Health as Mindful Minutes.`,
      priv_hero_title:`Privacy Policy`,
      priv_hero_sub:`How Study Sprint Timer handles your data.`,
      priv_updated:`Last updated: September 3, 2026`,
      priv_h1:`Overview`,
      priv_p1:`Study Sprint Timer ("the app") is an offline-first focus and Pomodoro study timer. We built it to respect your privacy. The app does not require an account and does not ask for your name, email, or any personal details to work.`,
      priv_h2:`Information We Collect`,
      priv_p2:`<strong>Your study data stays on your device.</strong> Sessions, books, streaks and goals are stored locally, and we never receive them. What does leave the device is described below: usage measurement, crash reports, and the data the ad and subscription providers need.`,
      priv_h3:`Advertising & Third-Party Services`,
      priv_p3:`The free version of the app displays ads through <strong>Google AdMob</strong>. To deliver and measure ads, Google may collect and process certain information, such as a device advertising identifier, IP address, and general usage data. This processing is performed by Google, not by us.`,
      priv_l3:`<li>We use Google's User Messaging Platform to request your consent where required.</li><li>On iOS, we show Apple's App Tracking Transparency prompt. If you do not allow tracking, the app still works fully and you may see less relevant ads.</li><li>Learn more in <a href="https://policies.google.com/privacy" target="_blank" rel="noopener">Google's Privacy Policy</a>.</li>`,
      priv_p3c:`We also use <strong>Google Firebase</strong>. It measures which screens and features get used, sends us a crash report when the app fails, delivers the announcement notifications you can turn on, and lets us change a few settings without shipping an update.`,
      priv_l3c:`<li>None of this carries your name, e-mail address or study notes.</li><li>Crash reports include the device model and iOS or Android version so we can reproduce the failure.</li><li>You can turn announcements off in Settings at any time.</li><li>Read <a href="https://firebase.google.com/support/privacy" target="_blank" rel="noopener">Firebase's privacy page</a> for the details.</li>`,
      priv_p3b:`Purchasing <strong>Premium</strong> removes all ads.`,
      priv_h4:`Purchases`,
      priv_p4:`Subscriptions and purchases are processed by <strong>Apple</strong> through the App Store. We never receive or store your payment information. To check whether your subscription is active, and to carry your sync code between your own devices, the app uses <strong>RevenueCat</strong>. RevenueCat receives the purchase events and an identifier the app generates; it never receives your payment details or your name. Apple's handling is governed by <a href="https://www.apple.com/legal/privacy/" target="_blank" rel="noopener">Apple's Privacy Policy</a> and <a href="https://www.revenuecat.com/privacy" target="_blank" rel="noopener">RevenueCat's Privacy Policy</a>.`,
      priv_h4b:`Apple Health (Optional)`,
      priv_p4b:`If you turn on Apple Health sync, the app writes your completed focus sessions to Apple Health as Mindful Minutes. Only the session duration is written; the app reads nothing from Health. Your Health data stays on your device under Apple's Health privacy protections, and you can turn this off anytime in iOS Settings → Health.`,
      priv_h4c:`Book Search (Optional)`,
      priv_p4c:`When you add a book to your library, the app can fill in its details for you. As you type a title, that text is sent to <strong>Open Library</strong> so the app can suggest matching titles, authors and page counts, and cover images are loaded from Open Library's servers. This happens only while you are typing in the search field. We never receive or store these searches, and you can ignore the suggestions and type everything yourself. Without an internet connection the search returns nothing and the rest of the app keeps working. Open Library is run by the Internet Archive; see their <a href="https://archive.org/about/terms.php" target="_blank" rel="noopener">privacy policy</a>.`,
      priv_h4d:`Apple Calendar (Optional)`,
      priv_p4d:`If you turn on calendar sync, the app writes each completed session into a separate "Study Sprint" calendar in your Calendar app. It only writes entries; it does not read your existing events and does not change your other calendars. Those entries stay in your own calendar account, so we never see them. You can turn the option off in the app's Settings, or revoke access in iOS Settings → Privacy & Security → Calendars.`,
      priv_h4e:`Focus Shield (Optional)`,
      priv_p4e:`Focus Shield keeps the apps you choose closed while a session runs. It uses Apple's Screen Time (Family Controls) framework, which asks for your permission the first time you turn it on. The apps you pick are stored on your device as tokens only iOS can read, so the list never reaches us. Turn the shield off in the app's Settings, or revoke the permission in iOS Settings → Screen Time.`,
      priv_h4f:`Game Center (Optional)`,
      priv_p4f:`If you sign in to Game Center, the app submits two numbers to the leaderboards: your focus minutes for the week and your longest streak. Those go to Apple under Apple's privacy policy, and we never see them. Staying signed out only costs you the leaderboards and achievements; everything else works the same.`,
      priv_h4g:`The Android Version`,
      priv_p4g:`On Android, purchases go through Google Play instead of Apple, and the app includes Firebase Analytics, which sends usage measurements to Google. Apple Health, Apple Calendar, the Apple Watch app and Focus Shield are iPhone features and have no Android counterpart. The rest of this policy holds for both versions: your study data stays on your device and we run no server of our own.`,
      priv_h5:`Data Sharing`,
      priv_p5:`We do not sell, rent, or trade your information. We do not share your locally stored study data with anyone.`,
      priv_h6:`Your Choices`,
      priv_l6:`<li>Manage tracking via iOS Settings → Privacy & Security → Tracking.</li><li>Reset your advertising identifier in iOS Settings.</li><li>Remove ads entirely by purchasing Premium.</li><li>Delete all local data anytime from the app's Settings → Clear Data, or by uninstalling the app.</li>`,
      priv_h7:`Children's Privacy`,
      priv_p7:`The app is not directed to children under 13 and we do not knowingly collect personal information from children.`,
      priv_h8:`Changes to This Policy`,
      priv_p8:`We may update this policy from time to time. Material changes will be reflected on this page with a new "Last updated" date.`,
      priv_h_rights:`Your Rights`,
      priv_p_rights:`<strong>Data controller:</strong> Harun Doğdu, <a href="mailto:support@studysprinttimer.com">support@studysprinttimer.com</a>. Under the GDPR and Turkish law no. 6698 (KVKK) you can ask what data is processed about you, ask for it to be corrected or deleted, object to the processing, and withdraw the consent you gave for ads and measurement. Ads, measurement and subscription checks run on Google, RevenueCat and Apple infrastructure, on servers outside Türkiye and, for users in Europe, outside the EEA. Your study data itself never leaves your device. We answer requests within 30 days.`,
      priv_h9:`Contact`,
      priv_p9:`Questions about this Privacy Policy? Contact us at <a href="mailto:support@studysprinttimer.com">support@studysprinttimer.com</a>.`,
      term_hero_title:`Terms of Service`,
      term_hero_sub:`The rules for using Study Sprint Timer.`,
      term_updated:`Last updated: September 3, 2026`,
      term_h1:`1. Acceptance of Terms`,
      term_p1:`By downloading or using Study Sprint Timer ("the app"), you agree to these Terms of Service. If you do not agree, please do not use the app.`,
      term_h2:`2. The Service`,
      term_p2:`Study Sprint Timer is an offline focus and Pomodoro study timer. It helps you run timed study sessions, track streaks, and stay motivated. The app works without an account and stores your data locally on your device.`,
      term_h3:`3. License`,
      term_p3:`We grant you a personal, non-transferable, non-exclusive license to use the app on Apple devices you own or control, in accordance with the Apple Media Services Terms and the standard <a href="https://www.apple.com/legal/internet-services/itunes/dev/stdeula/" target="_blank" rel="noopener">Apple End User License Agreement (EULA)</a>.`,
      term_h4:`4. Advertising`,
      term_p4:`The free version of the app displays advertisements provided by Google AdMob. By using the free version, you agree that ads may be shown. Purchasing Premium removes ads.`,
      term_h5:`5. Subscriptions & Purchases`,
      term_l5:`<li><strong>Premium</strong> is offered as monthly and yearly auto-renewable subscriptions.</li><li>Payment is charged to your Apple ID at confirmation of purchase.</li><li>Subscriptions renew automatically unless cancelled at least 24 hours before the end of the current period.</li><li>You can manage or cancel subscriptions anytime in your Apple ID account settings.</li><li>All purchases are processed and managed by Apple, subject to Apple's terms.</li><li>On Android, purchases are processed and managed by Google Play, subject to Google's terms.</li>`,
      term_h6:`6. Acceptable Use`,
      term_p6:`You agree to use the app only for lawful, personal purposes and not to misuse, reverse-engineer, or interfere with the app or its security.`,
      term_h7:`7. Health Disclaimer`,
      term_p7:`Study Sprint Timer is a productivity and focus tool. It does not provide medical, psychological, or professional advice, and should not be relied upon for any such purpose.`,
      term_h8:`8. Disclaimer of Warranties`,
      term_p8:`The app is provided "as is" and "as available" without warranties of any kind, to the maximum extent permitted by law. We do not guarantee that the app will be uninterrupted or error-free.`,
      term_h9:`9. Limitation of Liability`,
      term_p9:`To the maximum extent permitted by law, we are not liable for any indirect, incidental, or consequential damages arising from your use of the app.`,
      term_h10:`10. Changes to These Terms`,
      term_p10:`We may update these Terms from time to time. Continued use of the app after changes constitutes acceptance of the updated Terms.`,
      term_h11:`11. Contact`,
      term_p11:`Questions about these Terms? Contact us at <a href="mailto:support@studysprinttimer.com">support@studysprinttimer.com</a>.`,
      ft_desc:`Focus, Pomodoro & streaks — a simple offline study timer.`,
      ft_badge:`Available on the App Store`,
      ft_features:`Features`,
      ft_how:`How It Works`,
      ft_reviews:`Reviews`,
      ft_help:`Help Center`,
      ft_contact:`Contact Us`,
      ft_privacy:`Privacy Policy`,
      ft_terms:`Terms of Service`,
      ft_copy:`© 2026 Study Sprint Timer · Harun Doğdu`,
    },
    tr: {
      nav_home:`Ana Sayfa`,
      nav_privacy:`Gizlilik`,
      nav_terms:`Şartlar`,
      nav_support:`Destek`,
      nav_help:`Yardım Al`,
      nav_contact:`İletişim`,
      sup_hero_title:`Destek ve Yardım Merkezi`,
      sup_hero_sub:`Odaklanmana yardımcı olmak için buradayız.`,
      sup_get_title:`Bize ulaşın`,
      sup_get_desc:`Yardıma mı ihtiyacın var, bir hata mı buldun ya da bir fikrin mi var? Seni duymak isteriz.`,
      sup_get_btn:`Desteğe Yaz`,
      sup_or_pre:`Ya da doğrudan e-posta gönder:`,
      sup_or_post:`. Genellikle birkaç gün içinde yanıtlarız.`,
      sup_faq_title:`Sıkça Sorulan Sorular`,
      sup_q1:`Uygulama çevrimdışı çalışır mı?`,
      sup_a1:`Evet. Study Sprint Timer çevrimdışı önceliklidir — çalışma seanslarını yürütmek ve ilerlemeni takip etmek için hesap veya internet bağlantısı gerekmez.`,
      sup_q2:`Seriler nasıl çalışır?`,
      sup_a2:`Serini sürdürmek için o gün en az bir çalışma seansı tamamla. Bir günü kaçırırsan seri sıfırlanır — istikrarlı kalman için nazik bir dürtü.`,
      sup_q3:`Temayı nasıl değiştiririm?`,
      sup_a3:`Ayarlar → Tema'yı aç ve istediğin rengi seç. Desteklenen cihazlarda ana ekran uygulama ikonu seçtiğin temaya göre güncellenir.`,
      sup_q4:`Reklamları nasıl kaldırırım?`,
      sup_a4:`Uygulamadan Premium'a geç; reklamsız deneyimin tadını çıkar ve ekstra temaları aç.`,
      sup_q5:`Satın alımımı nasıl geri yüklerim?`,
      sup_a5:`Ayarlar → Satın Alımları Geri Yükle'ye git. İlk satın alımda kullandığın Apple Kimliği ile giriş yaptığından emin ol.`,
      sup_q6:`Verilerimi nasıl silerim?`,
      sup_a6:`Tüm veriler cihazında yerel olarak saklanır. Ayarlar → Verileri Temizle'den ya da uygulamayı kaldırarak her şeyi silebilirsin.`,
      sup_q7:`Apple Watch uygulaması var mı?`,
      sup_a7:`Evet. Watch uygulamasını kur, sprintleri bileğinden başlat; oturumlar iPhone'una otomatik işlenir.`,
      sup_q8:`Oturumları Apple Sağlık'a kaydedebilir miyim?`,
      sup_a8:`Evet. Ayarlar'dan "Apple Sağlık'a Yaz"ı aç; tamamlanan oturumlar Sağlık'ta Farkındalık Dakikası olarak görünür.`,
      priv_hero_title:`Gizlilik Politikası`,
      priv_hero_sub:`Study Sprint Timer verilerini nasıl işler.`,
      priv_updated:`Son güncelleme: 3 Eylül 2026`,
      priv_h1:`Genel Bakış`,
      priv_p1:`Study Sprint Timer ("uygulama") çevrimdışı öncelikli bir odak ve Pomodoro çalışma zamanlayıcısıdır. Gizliliğine saygı duyacak şekilde tasarlandı. Uygulama bir hesap gerektirmez; çalışmak için adını, e-postanı veya herhangi bir kişisel bilgini istemez.`,
      priv_h2:`Topladığımız Bilgiler`,
      priv_p2:`<strong>Çalışma verileriniz cihazınızda kalır.</strong> Oturumlar, kitaplar, seriler ve hedefler yalnızca cihazda saklanır; bunlar bize hiç ulaşmaz. Cihazdan çıkanlar aşağıda anlatılmıştır: kullanım ölçümü, hata raporları ve reklam ile abonelik sağlayıcılarının ihtiyaç duyduğu veriler.`,
      priv_h3:`Reklam ve Üçüncü Taraf Hizmetleri`,
      priv_p3:`Uygulamanın ücretsiz sürümü <strong>Google AdMob</strong> aracılığıyla reklam gösterir. Reklamları sunmak ve ölçmek için Google, cihaz reklam kimliği, IP adresi ve genel kullanım verileri gibi bazı bilgileri toplayıp işleyebilir. Bu işleme biz değil, Google tarafından yapılır.`,
      priv_l3:`<li>Gerektiğinde onayını istemek için Google'ın User Messaging Platform'unu kullanırız.</li><li>iOS'ta Apple'ın App Tracking Transparency istemini gösteririz. Takibe izin vermezsen uygulama tüm özellikleriyle çalışmaya devam eder ve daha az ilgili reklamlar görebilirsin.</li><li>Daha fazlası için <a href="https://policies.google.com/privacy" target="_blank" rel="noopener">Google Gizlilik Politikası</a>.</li>`,
      priv_p3c:`Ayrıca <strong>Google Firebase</strong> kullanıyoruz. Hangi ekranların ve özelliklerin kullanıldığını ölçüyor, uygulama çöktüğünde bize hata raporu gönderiyor, açtığınız takdirde duyuru bildirimlerini iletiyor ve birkaç ayarı yeni sürüm çıkarmadan değiştirmemizi sağlıyor.`,
      priv_l3c:`<li>Bunların hiçbiri adınızı, e-posta adresinizi veya çalışma notlarınızı taşımaz.</li><li>Hata raporunda cihaz modeli ve iOS ya da Android sürümü yer alır; çökmeyi yeniden üretebilmek için gerekli.</li><li>Duyuruları Ayarlar'dan istediğiniz zaman kapatabilirsiniz.</li><li>Ayrıntılar için <a href="https://firebase.google.com/support/privacy" target="_blank" rel="noopener">Firebase'in gizlilik sayfasına</a> bakabilirsiniz.</li>`,
      priv_p3b:`<strong>Premium</strong> satın almak tüm reklamları kaldırır.`,
      priv_h4:`Satın Alımlar`,
      priv_p4:`Abonelikler ve satın alımlar App Store üzerinden <strong>Apple</strong> tarafından işlenir. Ödeme bilgilerini asla almaz veya saklamayız. Aboneliğinin açık olup olmadığını görmek ve eşitleme kodunu kendi cihazların arasında taşımak için uygulama <strong>RevenueCat</strong> kullanır. RevenueCat'e satın alma olayları ve uygulamanın ürettiği bir kimlik gider; ödeme bilgilerin ve adın hiçbir zaman gitmez. Apple'ın işleyişi <a href="https://www.apple.com/legal/privacy/" target="_blank" rel="noopener">Apple Gizlilik Politikası</a> ile yönetilir ve <a href="https://www.revenuecat.com/privacy" target="_blank" rel="noopener">RevenueCat gizlilik politikası</a>.`,
      priv_h4b:`Apple Sağlık (İsteğe Bağlı)`,
      priv_p4b:`Apple Sağlık eşitlemesini açarsan uygulama, tamamlanan odak oturumlarını Apple Sağlık'a Farkındalık Dakikası olarak yazar. Yalnızca oturum süresi yazılır; uygulama Sağlık'tan hiçbir veri okumaz. Sağlık verilerin Apple'ın Sağlık gizlilik korumaları altında cihazında kalır; bunu istediğin an iOS Ayarlar → Sağlık'tan kapatabilirsin.`,
      priv_h4c:`Kitap Arama (İsteğe Bağlı)`,
      priv_p4c:`Kitaplığına kitap eklerken uygulama kitabın bilgilerini senin için doldurabilir. Başlığı yazdıkça bu metin <strong>Open Library</strong>'ye gönderilir; eşleşen kitap adları, yazarlar ve sayfa sayıları öneri olarak gelir, kapak görselleri de Open Library sunucularından yüklenir. Bu yalnızca sen arama alanına yazarken olur. Bu aramaları biz almıyor ve saklamıyoruz; önerileri hiç kullanmadan bilgileri kendin de girebilirsin. İnternet bağlantısı yoksa arama sonuç döndürmez ve uygulamanın geri kalanı normal çalışır. Open Library, Internet Archive tarafından işletiliyor; <a href="https://archive.org/about/terms.php" target="_blank" rel="noopener">gizlilik politikaları burada</a>.`,
      priv_h4d:`Apple Takvim (İsteğe Bağlı)`,
      priv_p4d:`Takvim eşitlemesini açarsan uygulama, tamamladığın her oturumu Takvim uygulamandaki ayrı bir "Study Sprint" takvimine yazar. Yalnızca kayıt ekler; mevcut etkinliklerini okumaz ve diğer takvimlerini değiştirmez. Bu kayıtlar senin kendi takvim hesabında kalır, biz görmeyiz. Seçeneği uygulamanın Ayarlar bölümünden kapatabilir, izni iOS Ayarlar → Gizlilik ve Güvenlik → Takvimler'den geri alabilirsin.`,
      priv_h4e:`Odak Kalkanı (İsteğe Bağlı)`,
      priv_p4e:`Odak Kalkanı, oturum sürerken seçtiğin uygulamaları kapalı tutar. Apple'ın Ekran Süresi (Family Controls) altyapısını kullanır ve ilk açtığında izin ister. Seçtiğin uygulamalar cihazında yalnızca iOS'un okuyabildiği simgeler olarak durur; liste bize hiç ulaşmaz. Kalkanı uygulamanın Ayarlar'ından kapatabilir, izni iOS Ayarlar → Ekran Süresi'nden geri alabilirsin.`,
      priv_h4f:`Game Center (İsteğe Bağlı)`,
      priv_p4f:`Game Center'a girersen uygulama liderlik tablolarına iki sayı gönderir: o haftaki odak dakikan ve en uzun serin. Bunlar Apple'a gider ve Apple'ın gizlilik politikasına tabidir; biz görmeyiz. Girmemenin tek bedeli liderlik tabloları ve başarımlardır, geri kalan her şey aynı çalışır.`,
      priv_h4g:`Android Sürümü`,
      priv_p4g:`Android'de satın almalar Apple yerine Google Play üzerinden işlenir ve uygulamada kullanım ölçümlerini Google'a gönderen Firebase Analytics bulunur. Apple Health, Apple Takvim, Apple Watch uygulaması ve Odak Kalkanı iPhone özellikleridir; Android'de karşılıkları yoktur. Bu politikanın geri kalanı iki sürüm için de geçerli: çalışma verin cihazında kalır ve bizim bir sunucumuz yoktur.`,
      priv_h5:`Veri Paylaşımı`,
      priv_p5:`Bilgilerini satmaz, kiralamaz veya takas etmeyiz. Cihazında yerel olarak saklanan çalışma verilerini hiç kimseyle paylaşmayız.`,
      priv_h6:`Tercihlerin`,
      priv_l6:`<li>Takibi iOS Ayarlar → Gizlilik ve Güvenlik → İzleme'den yönet.</li><li>Reklam kimliğini iOS Ayarlar'dan sıfırla.</li><li>Premium satın alarak reklamları tamamen kaldır.</li><li>Tüm yerel verileri istediğin an uygulamanın Ayarlar → Verileri Temizle bölümünden ya da uygulamayı kaldırarak sil.</li>`,
      priv_h7:`Çocukların Gizliliği`,
      priv_p7:`Uygulama 13 yaşından küçük çocuklara yönelik değildir ve çocuklardan bilerek kişisel bilgi toplamayız.`,
      priv_h8:`Bu Politikadaki Değişiklikler`,
      priv_p8:`Bu politikayı zaman zaman güncelleyebiliriz. Önemli değişiklikler yeni bir "Son güncelleme" tarihiyle bu sayfada yansıtılır.`,
      priv_h_rights:`Haklarınız`,
      priv_p_rights:`<strong>Veri sorumlusu:</strong> Harun Doğdu, <a href="mailto:support@studysprinttimer.com">support@studysprinttimer.com</a>. 6698 sayılı KVKK'nın 11. maddesi ve Avrupa'da GDPR uyarınca hakkınızda işlenen veriler konusunda bilgi isteyebilir, düzeltilmesini ya da silinmesini isteyebilir, işlemeye itiraz edebilir ve reklam ile ölçüm için verdiğiniz rızayı geri çekebilirsiniz. Reklam, ölçüm ve abonelik doğrulaması Google, RevenueCat ve Apple altyapısında, Türkiye dışındaki sunucularda işlenir. Çalışma verileriniz cihazınızdan hiç çıkmaz. Başvurular en geç 30 gün içinde yanıtlanır.`,
      priv_h9:`İletişim`,
      priv_p9:`Bu Gizlilik Politikası hakkında sorun mu var? Bize <a href="mailto:support@studysprinttimer.com">support@studysprinttimer.com</a> adresinden ulaş.`,
      term_hero_title:`Kullanım Şartları`,
      term_hero_sub:`Study Sprint Timer'ı kullanma kuralları.`,
      term_updated:`Son güncelleme: 3 Eylül 2026`,
      term_h1:`1. Şartların Kabulü`,
      term_p1:`Study Sprint Timer'ı ("uygulama") indirerek veya kullanarak bu Kullanım Şartları'nı kabul etmiş olursun. Kabul etmiyorsan lütfen uygulamayı kullanma.`,
      term_h2:`2. Hizmet`,
      term_p2:`Study Sprint Timer çevrimdışı bir odak ve Pomodoro çalışma zamanlayıcısıdır. Zamanlı çalışma seansları yürütmene, serileri takip etmene ve motive kalmana yardımcı olur. Uygulama hesapsız çalışır ve verilerini cihazında yerel olarak saklar.`,
      term_h3:`3. Lisans`,
      term_p3:`Sahibi olduğun veya kontrol ettiğin Apple cihazlarında uygulamayı kullanman için Apple Media Services Şartları ve standart <a href="https://www.apple.com/legal/internet-services/itunes/dev/stdeula/" target="_blank" rel="noopener">Apple Son Kullanıcı Lisans Sözleşmesi (EULA)</a> uyarınca kişisel, devredilemez ve münhasır olmayan bir lisans veririz.`,
      term_h4:`4. Reklam`,
      term_p4:`Uygulamanın ücretsiz sürümü Google AdMob tarafından sağlanan reklamlar gösterir. Ücretsiz sürümü kullanarak reklam gösterilebileceğini kabul edersin. Premium satın almak reklamları kaldırır.`,
      term_h5:`5. Abonelikler ve Satın Alımlar`,
      term_l5:`<li><strong>Premium</strong>, aylık ve yıllık otomatik yenilenen abonelikler olarak sunulur.</li><li>Ödeme, satın alım onayında Apple Kimliğine tahsil edilir.</li><li>Abonelikler, mevcut dönemin bitiminden en az 24 saat önce iptal edilmediği sürece otomatik yenilenir.</li><li>Abonelikleri istediğin an Apple Kimliği hesap ayarlarından yönetebilir veya iptal edebilirsin.</li><li>Tüm satın alımlar Apple tarafından, Apple'ın şartlarına tabi olarak işlenir ve yönetilir.</li><li>Android'de satın alımlar Google Play tarafından, Google'ın şartlarına tabi olarak işlenir ve yönetilir.</li>`,
      term_h6:`6. Kabul Edilebilir Kullanım`,
      term_p6:`Uygulamayı yalnızca yasal ve kişisel amaçlarla kullanmayı; kötüye kullanmamayı, tersine mühendislik yapmamayı ya da uygulamaya veya güvenliğine müdahale etmemeyi kabul edersin.`,
      term_h7:`7. Sağlık Sorumluluk Reddi`,
      term_p7:`Study Sprint Timer bir verimlilik ve odak aracıdır. Tıbbi, psikolojik veya profesyonel tavsiye vermez ve böyle bir amaçla kullanılmamalıdır.`,
      term_h8:`8. Garanti Reddi`,
      term_p8:`Uygulama, yasaların izin verdiği azami ölçüde, hiçbir garanti olmaksızın "olduğu gibi" ve "mevcut olduğu şekilde" sunulur. Uygulamanın kesintisiz veya hatasız olacağını garanti etmeyiz.`,
      term_h9:`9. Sorumluluğun Sınırlandırılması`,
      term_p9:`Yasaların izin verdiği azami ölçüde, uygulamayı kullanmandan doğan dolaylı, arızi veya sonuçsal zararlardan sorumlu değiliz.`,
      term_h10:`10. Bu Şartlardaki Değişiklikler`,
      term_p10:`Bu Şartları zaman zaman güncelleyebiliriz. Değişikliklerden sonra uygulamayı kullanmaya devam etmen güncellenmiş Şartları kabul ettiğin anlamına gelir.`,
      term_h11:`11. İletişim`,
      term_p11:`Bu Şartlar hakkında sorun mu var? Bize <a href="mailto:support@studysprinttimer.com">support@studysprinttimer.com</a> adresinden ulaş.`,
      ft_desc:`Odak, Pomodoro ve seriler — basit, çevrimdışı bir çalışma zamanlayıcısı.`,
      ft_badge:`App Store'da`,
      ft_features:`Özellikler`,
      ft_how:`Nasıl Çalışır`,
      ft_reviews:`Yorumlar`,
      ft_help:`Yardım Merkezi`,
      ft_contact:`Bize Ulaşın`,
      ft_privacy:`Gizlilik Politikası`,
      ft_terms:`Kullanım Şartları`,
      ft_copy:`© 2026 Study Sprint Timer · Harun Doğdu`,
    },
    de: {
      nav_home:`Start`,
      nav_privacy:`Datenschutz`,
      nav_terms:`Bedingungen`,
      nav_support:`Support`,
      nav_help:`Hilfe`,
      nav_contact:`Kontakt`,
      sup_hero_title:`Support & Hilfe-Center`,
      sup_hero_sub:`Wir helfen dir, dich zu konzentrieren.`,
      sup_get_title:`Kontakt aufnehmen`,
      sup_get_desc:`Brauchst du Hilfe, hast du einen Fehler gefunden oder eine Idee? Wir freuen uns, von dir zu hören.`,
      sup_get_btn:`Support kontaktieren`,
      sup_or_pre:`Oder schreib uns direkt an`,
      sup_or_post:`. Wir antworten meist innerhalb weniger Tage.`,
      sup_faq_title:`Häufig gestellte Fragen`,
      sup_q1:`Funktioniert die App offline?`,
      sup_a1:`Ja. Study Sprint Timer ist offline-first — für Lernsessions und das Verfolgen deines Fortschritts sind kein Konto und keine Internetverbindung nötig.`,
      sup_q2:`Wie funktionieren Serien?`,
      sup_a2:`Schließe an einem Tag mindestens eine Lernsession ab, um deine Serie fortzuführen. Verpasst du einen Tag, wird sie zurückgesetzt — ein sanfter Anstoß, dranzubleiben.`,
      sup_q3:`Wie ändere ich das Theme?`,
      sup_a3:`Öffne Einstellungen → Theme und wähle eine Farbe. Auf unterstützten Geräten passt sich sogar das App-Icon deinem Theme an.`,
      sup_q4:`Wie entferne ich Werbung?`,
      sup_a4:`Wechsle in der App zu Premium für ein werbefreies Erlebnis und zusätzliche Themes.`,
      sup_q5:`Wie stelle ich meinen Kauf wieder her?`,
      sup_a5:`Gehe zu Einstellungen → Käufe wiederherstellen. Melde dich mit derselben Apple-ID an, mit der du gekauft hast.`,
      sup_q6:`Wie lösche ich meine Daten?`,
      sup_a6:`Alle Daten werden lokal gespeichert. Du kannst alles über Einstellungen → Daten löschen oder durch Deinstallation der App entfernen.`,
      sup_q7:`Gibt es eine Apple-Watch-App?`,
      sup_a7:`Ja. Installiere die Watch-App und starte Sprints vom Handgelenk; Sitzungen werden automatisch mit deinem iPhone synchronisiert.`,
      sup_q8:`Kann ich Sitzungen in Apple Health speichern?`,
      sup_a8:`Ja. Aktiviere „In Apple Health schreiben" in den Einstellungen; abgeschlossene Sitzungen erscheinen in Health als Achtsamkeitsminuten.`,
      priv_hero_title:`Datenschutzerklärung`,
      priv_hero_sub:`Wie Study Sprint Timer mit deinen Daten umgeht.`,
      priv_updated:`Zuletzt aktualisiert: 3. September 2026`,
      priv_h1:`Überblick`,
      priv_p1:`Study Sprint Timer ("die App") ist ein offline-first Fokus- und Pomodoro-Lerntimer. Wir haben ihn so gebaut, dass er deine Privatsphäre respektiert. Die App benötigt kein Konto und fragt nicht nach Namen, E-Mail oder anderen persönlichen Daten.`,
      priv_h2:`Erhobene Informationen`,
      priv_p2:`<strong>Deine Lerndaten bleiben auf dem Gerät.</strong> Sitzungen, Bücher, Serien und Ziele werden nur lokal gespeichert und erreichen uns nie. Was das Gerät verlässt, steht weiter unten: Nutzungsmessung, Absturzberichte und die Daten, die Werbe- und Abo-Anbieter benötigen.`,
      priv_h3:`Werbung & Drittanbieter`,
      priv_p3:`Die kostenlose Version zeigt Werbung über <strong>Google AdMob</strong>. Zur Auslieferung und Messung kann Google bestimmte Informationen erheben, etwa eine Werbe-ID, IP-Adresse und allgemeine Nutzungsdaten. Diese Verarbeitung erfolgt durch Google, nicht durch uns.`,
      priv_l3:`<li>Wir nutzen Googles User Messaging Platform, um wo nötig deine Einwilligung einzuholen.</li><li>Auf iOS zeigen wir Apples App-Tracking-Transparenz-Dialog. Lehnst du das Tracking ab, funktioniert die App voll und du siehst ggf. weniger relevante Werbung.</li><li>Mehr in der <a href="https://policies.google.com/privacy" target="_blank" rel="noopener">Datenschutzerklärung von Google</a>.</li>`,
      priv_p3c:`Wir nutzen außerdem <strong>Google Firebase</strong>. Es misst, welche Bildschirme und Funktionen verwendet werden, schickt uns einen Absturzbericht, wenn die App abstürzt, stellt die Ankündigungen zu, die du einschalten kannst, und lässt uns einige Einstellungen ändern, ohne ein Update zu veröffentlichen.`,
      priv_l3c:`<li>Nichts davon enthält deinen Namen, deine E-Mail-Adresse oder deine Lernnotizen.</li><li>Absturzberichte enthalten Gerätemodell und iOS- bzw. Android-Version, damit wir den Fehler nachstellen können.</li><li>Ankündigungen kannst du jederzeit in den Einstellungen ausschalten.</li><li>Einzelheiten stehen auf <a href="https://firebase.google.com/support/privacy" target="_blank" rel="noopener">Firebases Datenschutzseite</a>.</li>`,
      priv_p3b:`Der Kauf von <strong>Premium</strong> entfernt jede Werbung.`,
      priv_h4:`Käufe`,
      priv_p4:`Abos und Käufe werden von <strong>Apple</strong> über den App Store abgewickelt. Wir erhalten oder speichern niemals deine Zahlungsdaten. Um zu prüfen, ob dein Abo aktiv ist, und um deinen Sync-Code zwischen deinen eigenen Geräten mitzunehmen, nutzt die App <strong>RevenueCat</strong>. RevenueCat erhält die Kaufereignisse und eine von der App erzeugte Kennung; deine Zahlungsdaten und deinen Namen erhält der Dienst nie. Apples Umgang unterliegt der <a href="https://www.apple.com/legal/privacy/" target="_blank" rel="noopener">Datenschutzerklärung von Apple</a> und die <a href="https://www.revenuecat.com/privacy" target="_blank" rel="noopener">Datenschutzerklärung von RevenueCat</a>.`,
      priv_h4b:`Apple Health (optional)`,
      priv_p4b:`Wenn du die Apple-Health-Synchronisierung aktivierst, schreibt die App deine abgeschlossenen Fokussitzungen als Achtsamkeitsminuten in Apple Health. Es wird nur die Sitzungsdauer geschrieben; die App liest nichts aus Health. Deine Health-Daten bleiben unter Apples Health-Datenschutz auf deinem Gerät; du kannst das jederzeit in den iOS-Einstellungen → Health deaktivieren.`,
      priv_h4c:`Buchsuche (optional)`,
      priv_p4c:`Wenn du ein Buch zu deiner Bibliothek hinzufügst, kann die App die Angaben für dich ausfüllen. Während du einen Titel eintippst, wird dieser Text an <strong>Open Library</strong> gesendet, damit die App passende Titel, Autoren und Seitenzahlen vorschlagen kann; die Cover werden von den Servern von Open Library geladen. Das passiert nur, solange du im Suchfeld tippst. Wir erhalten und speichern diese Suchanfragen nicht, und du kannst die Vorschläge ignorieren und alles selbst eintragen. Ohne Internetverbindung liefert die Suche nichts und der Rest der App funktioniert normal weiter. Open Library wird vom Internet Archive betrieben; siehe deren <a href="https://archive.org/about/terms.php" target="_blank" rel="noopener">Datenschutzerklärung</a>.`,
      priv_h4d:`Apple Kalender (optional)`,
      priv_p4d:`Wenn du die Kalender-Synchronisierung aktivierst, schreibt die App jede abgeschlossene Sitzung in einen separaten Kalender namens "Study Sprint" in deiner Kalender-App. Sie schreibt nur Einträge; sie liest deine vorhandenen Termine nicht und verändert deine anderen Kalender nicht. Die Einträge bleiben in deinem eigenen Kalenderkonto, wir sehen sie also nie. Du kannst die Option in den Einstellungen der App deaktivieren oder den Zugriff in den iOS-Einstellungen → Datenschutz & Sicherheit → Kalender entziehen.`,
      priv_h4e:`Fokus-Schild (optional)`,
      priv_p4e:`Das Fokus-Schild hält die von dir gewählten Apps während einer Sitzung geschlossen. Es nutzt Apples Bildschirmzeit (Family Controls), die beim ersten Einschalten um Erlaubnis bittet. Die gewählten Apps liegen als Tokens auf deinem Gerät, die nur iOS lesen kann; die Liste erreicht uns nie. Das Schild schaltest du in den Einstellungen der App aus, die Erlaubnis entziehst du unter iOS-Einstellungen → Bildschirmzeit.`,
      priv_h4f:`Game Center (optional)`,
      priv_p4f:`Meldest du dich bei Game Center an, sendet die App zwei Zahlen an die Bestenlisten: deine Fokusminuten der Woche und deine längste Serie. Sie gehen an Apple und unterliegen Apples Datenschutzerklärung; wir sehen sie nie. Wer abgemeldet bleibt, verzichtet nur auf Bestenlisten und Erfolge, alles andere funktioniert gleich.`,
      priv_h4g:`Die Android-Fassung`,
      priv_p4g:`Unter Android laufen Käufe über Google Play statt über Apple, und die App enthält Firebase Analytics, das Nutzungsmessungen an Google sendet. Apple Health, Apple Kalender, die Apple-Watch-App und das Fokus-Schild sind iPhone-Funktionen und haben unter Android kein Gegenstück. Der Rest dieser Erklärung gilt für beide Fassungen: deine Lerndaten bleiben auf dem Gerät, und einen eigenen Server betreiben wir nicht.`,
      priv_h5:`Datenweitergabe`,
      priv_p5:`Wir verkaufen, vermieten oder handeln nicht mit deinen Informationen. Wir geben deine lokal gespeicherten Lerndaten an niemanden weiter.`,
      priv_h6:`Deine Optionen`,
      priv_l6:`<li>Tracking über iOS Einstellungen → Datenschutz & Sicherheit → Tracking verwalten.</li><li>Werbe-ID in den iOS-Einstellungen zurücksetzen.</li><li>Werbung durch den Kauf von Premium vollständig entfernen.</li><li>Alle lokalen Daten jederzeit über Einstellungen → Daten löschen oder durch Deinstallation entfernen.</li>`,
      priv_h7:`Datenschutz für Kinder`,
      priv_p7:`Die App richtet sich nicht an Kinder unter 13 Jahren und wir erheben wissentlich keine personenbezogenen Daten von Kindern.`,
      priv_h8:`Änderungen dieser Richtlinie`,
      priv_p8:`Wir können diese Richtlinie gelegentlich aktualisieren. Wesentliche Änderungen erscheinen auf dieser Seite mit einem neuen "Zuletzt aktualisiert"-Datum.`,
      priv_h_rights:`Deine Rechte`,
      priv_p_rights:`<strong>Verantwortlicher:</strong> Harun Doğdu, <a href="mailto:support@studysprinttimer.com">support@studysprinttimer.com</a>. Nach der DSGVO und dem türkischen Gesetz Nr. 6698 (KVKK) kannst du Auskunft über die zu dir verarbeiteten Daten verlangen, deren Berichtigung oder Löschung fordern, der Verarbeitung widersprechen und deine Einwilligung für Werbung und Messung widerrufen. Werbung, Messung und Abo-Prüfung laufen über die Infrastruktur von Google, RevenueCat und Apple, auf Servern außerhalb der Türkei und außerhalb des EWR. Deine Lerndaten selbst verlassen dein Gerät nie. Wir antworten innerhalb von 30 Tagen.`,
      priv_h9:`Kontakt`,
      priv_p9:`Fragen zu dieser Datenschutzerklärung? Kontaktiere uns unter <a href="mailto:support@studysprinttimer.com">support@studysprinttimer.com</a>.`,
      term_hero_title:`Nutzungsbedingungen`,
      term_hero_sub:`Die Regeln zur Nutzung von Study Sprint Timer.`,
      term_updated:`Zuletzt aktualisiert: 3. September 2026`,
      term_h1:`1. Annahme der Bedingungen`,
      term_p1:`Durch Herunterladen oder Nutzen von Study Sprint Timer ("die App") stimmst du diesen Nutzungsbedingungen zu. Wenn du nicht zustimmst, nutze die App bitte nicht.`,
      term_h2:`2. Der Dienst`,
      term_p2:`Study Sprint Timer ist ein offline Fokus- und Pomodoro-Lerntimer. Er hilft dir, getaktete Lernsessions durchzuführen, Serien zu verfolgen und motiviert zu bleiben. Die App funktioniert ohne Konto und speichert deine Daten lokal.`,
      term_h3:`3. Lizenz`,
      term_p3:`Wir gewähren dir eine persönliche, nicht übertragbare, nicht exklusive Lizenz zur Nutzung der App auf Apple-Geräten, die du besitzt oder kontrollierst, gemäß den Apple-Media-Services-Bedingungen und dem standardmäßigen <a href="https://www.apple.com/legal/internet-services/itunes/dev/stdeula/" target="_blank" rel="noopener">Apple-Endnutzer-Lizenzvertrag (EULA)</a>.`,
      term_h4:`4. Werbung`,
      term_p4:`Die kostenlose Version zeigt Werbung von Google AdMob. Durch die Nutzung der kostenlosen Version stimmst du zu, dass Werbung angezeigt werden kann. Der Kauf von Premium entfernt Werbung.`,
      term_h5:`5. Abos & Käufe`,
      term_l5:`<li><strong>Premium</strong> gibt es als monatliches oder jährliches, sich automatisch verlängerndes Abo.</li><li>Die Zahlung wird bei Kaufbestätigung deiner Apple-ID belastet.</li><li>Abos verlängern sich automatisch, sofern nicht mindestens 24 Stunden vor Periodenende gekündigt.</li><li>Du kannst Abos jederzeit in den Einstellungen deiner Apple-ID verwalten oder kündigen.</li><li>Alle Käufe werden von Apple gemäß Apples Bedingungen abgewickelt.</li><li>Unter Android werden Käufe von Google Play abgewickelt und verwaltet, nach den Bedingungen von Google.</li>`,
      term_h6:`6. Zulässige Nutzung`,
      term_p6:`Du verpflichtest dich, die App nur für rechtmäßige, persönliche Zwecke zu nutzen und sie oder ihre Sicherheit nicht zu missbrauchen, zurückzuentwickeln oder zu stören.`,
      term_h7:`7. Gesundheitshinweis`,
      term_p7:`Study Sprint Timer ist ein Produktivitäts- und Fokus-Tool. Es bietet keine medizinische, psychologische oder professionelle Beratung und sollte dafür nicht herangezogen werden.`,
      term_h8:`8. Gewährleistungsausschluss`,
      term_p8:`Die App wird im gesetzlich zulässigen Umfang "wie besehen" und "wie verfügbar" ohne jegliche Gewährleistung bereitgestellt. Wir garantieren keinen unterbrechungs- oder fehlerfreien Betrieb.`,
      term_h9:`9. Haftungsbeschränkung`,
      term_p9:`Im gesetzlich zulässigen Umfang haften wir nicht für indirekte, zufällige oder Folgeschäden, die aus der Nutzung der App entstehen.`,
      term_h10:`10. Änderungen dieser Bedingungen`,
      term_p10:`Wir können diese Bedingungen gelegentlich aktualisieren. Die fortgesetzte Nutzung nach Änderungen gilt als Annahme der aktualisierten Bedingungen.`,
      term_h11:`11. Kontakt`,
      term_p11:`Fragen zu diesen Bedingungen? Kontaktiere uns unter <a href="mailto:support@studysprinttimer.com">support@studysprinttimer.com</a>.`,
      ft_desc:`Fokus, Pomodoro & Serien — ein einfacher, offline Lern-Timer.`,
      ft_badge:`Im App Store`,
      ft_features:`Funktionen`,
      ft_how:`So funktioniert's`,
      ft_reviews:`Bewertungen`,
      ft_help:`Hilfe-Center`,
      ft_contact:`Kontakt`,
      ft_privacy:`Datenschutz`,
      ft_terms:`Nutzungsbedingungen`,
      ft_copy:`© 2026 Study Sprint Timer · Harun Doğdu`,
    },
    es: {
      nav_home:`Inicio`,
      nav_privacy:`Privacidad`,
      nav_terms:`Términos`,
      nav_support:`Soporte`,
      nav_help:`Ayuda`,
      nav_contact:`Contacto`,
      sup_hero_title:`Soporte y centro de ayuda`,
      sup_hero_sub:`Estamos aquí para ayudarte a concentrarte.`,
      sup_get_title:`Ponte en contacto`,
      sup_get_desc:`¿Necesitas ayuda, encontraste un error o tienes una idea? Nos encantaría saber de ti.`,
      sup_get_btn:`Contactar soporte`,
      sup_or_pre:`O escríbenos directamente a`,
      sup_or_post:`. Normalmente respondemos en pocos días.`,
      sup_faq_title:`Preguntas frecuentes`,
      sup_q1:`¿La app funciona sin conexión?`,
      sup_a1:`Sí. Study Sprint Timer funciona sin conexión — no se necesita cuenta ni internet para hacer sesiones de estudio y seguir tu progreso.`,
      sup_q2:`¿Cómo funcionan las rachas?`,
      sup_a2:`Completa al menos una sesión de estudio en el día para mantener tu racha. Si te saltas un día, se reinicia — un empujón suave para ser constante.`,
      sup_q3:`¿Cómo cambio el tema?`,
      sup_a3:`Abre Ajustes → Tema y elige el color que quieras. En dispositivos compatibles, el icono de la app cambia para combinar con tu tema.`,
      sup_q4:`¿Cómo quito los anuncios?`,
      sup_a4:`Pasa a Premium desde la app para disfrutar sin anuncios y desbloquear temas adicionales.`,
      sup_q5:`¿Cómo restauro mi compra?`,
      sup_a5:`Ve a Ajustes → Restaurar compras. Asegúrate de iniciar sesión con el mismo Apple ID que usaste al comprar.`,
      sup_q6:`¿Cómo elimino mis datos?`,
      sup_a6:`Todos los datos se guardan localmente. Puedes borrar todo en Ajustes → Borrar datos, o desinstalando la app.`,
      sup_q7:`¿Hay una app para Apple Watch?`,
      sup_a7:`Sí. Instala la app del Watch y empieza sprints desde tu muñeca; las sesiones se sincronizan automáticamente con tu iPhone.`,
      sup_q8:`¿Puedo guardar sesiones en Apple Health?`,
      sup_a8:`Sí. Activa "Guardar en Apple Health" en Ajustes; las sesiones completadas aparecen en Health como minutos de atención plena.`,
      priv_hero_title:`Política de privacidad`,
      priv_hero_sub:`Cómo Study Sprint Timer gestiona tus datos.`,
      priv_updated:`Última actualización: 3 de septiembre de 2026`,
      priv_h1:`Resumen`,
      priv_p1:`Study Sprint Timer ("la app") es un temporizador de estudio de enfoque y Pomodoro sin conexión. Lo creamos para respetar tu privacidad. La app no requiere cuenta ni pide tu nombre, correo ni datos personales para funcionar.`,
      priv_h2:`Información que recopilamos`,
      priv_p2:`<strong>Tus datos de estudio se quedan en el dispositivo.</strong> Las sesiones, los libros, las rachas y los objetivos se guardan solo ahí y nunca llegan a nosotros. Lo que sí sale del dispositivo se explica más abajo: medición de uso, informes de fallos y los datos que necesitan los proveedores de anuncios y suscripciones.`,
      priv_h3:`Publicidad y servicios de terceros`,
      priv_p3:`La versión gratuita muestra anuncios mediante <strong>Google AdMob</strong>. Para mostrar y medir anuncios, Google puede recopilar y procesar cierta información, como un identificador de publicidad, la dirección IP y datos de uso generales. Este procesamiento lo realiza Google, no nosotros.`,
      priv_l3:`<li>Usamos la User Messaging Platform de Google para solicitar tu consentimiento cuando corresponde.</li><li>En iOS mostramos el aviso de Transparencia de seguimiento de apps de Apple. Si no permites el seguimiento, la app sigue funcionando por completo y podrías ver anuncios menos relevantes.</li><li>Más información en la <a href="https://policies.google.com/privacy" target="_blank" rel="noopener">Política de privacidad de Google</a>.</li>`,
      priv_p3c:`También usamos <strong>Google Firebase</strong>. Mide qué pantallas y funciones se usan, nos envía un informe cuando la app falla, entrega los avisos que puedes activar y nos permite cambiar algunos parámetros sin publicar una actualización.`,
      priv_l3c:`<li>Nada de esto lleva tu nombre, tu correo ni tus notas de estudio.</li><li>Los informes de fallo incluyen el modelo del dispositivo y la versión de iOS o Android para poder reproducir el error.</li><li>Puedes desactivar los avisos en Ajustes cuando quieras.</li><li>Los detalles están en <a href="https://firebase.google.com/support/privacy" target="_blank" rel="noopener">la página de privacidad de Firebase</a>.</li>`,
      priv_p3b:`Comprar <strong>Premium</strong> elimina todos los anuncios.`,
      priv_h4:`Compras`,
      priv_p4:`Las suscripciones y compras las procesa <strong>Apple</strong> a través de la App Store. Nunca recibimos ni almacenamos tu información de pago. Para comprobar si tu suscripción está activa y para llevar tu código de sincronización entre tus propios dispositivos, la app usa <strong>RevenueCat</strong>. RevenueCat recibe los eventos de compra y un identificador que genera la app; nunca recibe tus datos de pago ni tu nombre. La gestión de Apple se rige por la <a href="https://www.apple.com/legal/privacy/" target="_blank" rel="noopener">Política de privacidad de Apple</a> y la <a href="https://www.revenuecat.com/privacy" target="_blank" rel="noopener">política de privacidad de RevenueCat</a>.`,
      priv_h4b:`Apple Health (opcional)`,
      priv_p4b:`Si activas la sincronización con Apple Health, la app guarda tus sesiones de enfoque completadas en Apple Health como minutos de atención plena. Solo se escribe la duración de la sesión; la app no lee nada de Health. Tus datos de Health permanecen en tu dispositivo bajo las protecciones de privacidad de Apple, y puedes desactivarlo cuando quieras en Ajustes de iOS → Salud.`,
      priv_h4c:`Búsqueda de libros (opcional)`,
      priv_p4c:`Cuando añades un libro a tu biblioteca, la app puede completar sus datos por ti. Mientras escribes un título, ese texto se envía a <strong>Open Library</strong> para que la app sugiera títulos, autores y número de páginas; las portadas se cargan desde los servidores de Open Library. Esto ocurre solo mientras escribes en el campo de búsqueda. No recibimos ni guardamos esas búsquedas, y puedes ignorar las sugerencias y escribirlo todo tú. Sin conexión a internet la búsqueda no devuelve nada y el resto de la app sigue funcionando. Open Library está gestionada por Internet Archive; consulta su <a href="https://archive.org/about/terms.php" target="_blank" rel="noopener">política de privacidad</a>.`,
      priv_h4d:`Calendario de Apple (opcional)`,
      priv_p4d:`Si activas la sincronización con el calendario, la app escribe cada sesión completada en un calendario aparte llamado "Study Sprint" dentro de tu app Calendario. Solo escribe entradas: no lee tus eventos existentes ni modifica tus otros calendarios. Esas entradas permanecen en tu propia cuenta de calendario, así que nunca las vemos. Puedes desactivar la opción en los Ajustes de la app o retirar el permiso en Ajustes de iOS → Privacidad y seguridad → Calendarios.`,
      priv_h4e:`Escudo de concentración (opcional)`,
      priv_p4e:`El escudo de concentración mantiene cerradas las apps que elijas mientras corre una sesión. Usa Tiempo de uso (Family Controls) de Apple, que pide permiso la primera vez que lo activas. Las apps que eliges se guardan en tu dispositivo como identificadores que solo iOS puede leer, así que la lista nunca llega hasta nosotros. Puedes apagar el escudo en los Ajustes de la app o retirar el permiso en Ajustes de iOS → Tiempo de uso.`,
      priv_h4f:`Game Center (opcional)`,
      priv_p4f:`Si inicias sesión en Game Center, la app envía dos cifras a las tablas de clasificación: tus minutos de concentración de la semana y tu racha más larga. Van a Apple bajo su política de privacidad y nosotros no las vemos. No iniciar sesión solo te deja sin tablas ni logros; el resto funciona igual.`,
      priv_h4g:`La versión de Android`,
      priv_p4g:`En Android las compras pasan por Google Play en lugar de Apple, y la app incluye Firebase Analytics, que envía mediciones de uso a Google. Apple Salud, el Calendario de Apple, la app de Apple Watch y el escudo de concentración son funciones de iPhone y no tienen equivalente en Android. El resto de esta política vale para las dos versiones: tus datos de estudio se quedan en tu dispositivo y no tenemos ningún servidor propio.`,
      priv_h5:`Uso compartido de datos`,
      priv_p5:`No vendemos, alquilamos ni intercambiamos tu información. No compartimos con nadie tus datos de estudio guardados localmente.`,
      priv_h6:`Tus opciones`,
      priv_l6:`<li>Gestiona el seguimiento en Ajustes de iOS → Privacidad y seguridad → Seguimiento.</li><li>Restablece tu identificador de publicidad en Ajustes de iOS.</li><li>Elimina los anuncios por completo comprando Premium.</li><li>Borra todos los datos locales cuando quieras desde Ajustes → Borrar datos, o desinstalando la app.</li>`,
      priv_h7:`Privacidad de los niños`,
      priv_p7:`La app no está dirigida a menores de 13 años y no recopilamos conscientemente información personal de niños.`,
      priv_h8:`Cambios en esta política`,
      priv_p8:`Podemos actualizar esta política de vez en cuando. Los cambios importantes se reflejarán en esta página con una nueva fecha de "Última actualización".`,
      priv_h_rights:`Tus derechos`,
      priv_p_rights:`<strong>Responsable del tratamiento:</strong> Harun Doğdu, <a href="mailto:support@studysprinttimer.com">support@studysprinttimer.com</a>. Según el RGPD y la ley turca n.º 6698 (KVKK) puedes preguntar qué datos se tratan sobre ti, pedir que se corrijan o se eliminen, oponerte al tratamiento y retirar el consentimiento que diste para anuncios y medición. Los anuncios, la medición y la verificación de la suscripción se procesan en la infraestructura de Google, RevenueCat y Apple, en servidores fuera de Türkiye y, para usuarios de Europa, fuera del EEE. Tus datos de estudio nunca salen del dispositivo. Respondemos en 30 días.`,
      priv_h9:`Contacto`,
      priv_p9:`¿Preguntas sobre esta Política de privacidad? Escríbenos a <a href="mailto:support@studysprinttimer.com">support@studysprinttimer.com</a>.`,
      term_hero_title:`Términos del servicio`,
      term_hero_sub:`Las reglas para usar Study Sprint Timer.`,
      term_updated:`Última actualización: 3 de septiembre de 2026`,
      term_h1:`1. Aceptación de los términos`,
      term_p1:`Al descargar o usar Study Sprint Timer ("la app"), aceptas estos Términos del servicio. Si no estás de acuerdo, no uses la app.`,
      term_h2:`2. El servicio`,
      term_p2:`Study Sprint Timer es un temporizador de estudio de enfoque y Pomodoro sin conexión. Te ayuda a hacer sesiones cronometradas, seguir rachas y mantener la motivación. Funciona sin cuenta y guarda tus datos localmente.`,
      term_h3:`3. Licencia`,
      term_p3:`Te concedemos una licencia personal, intransferible y no exclusiva para usar la app en dispositivos Apple que poseas o controles, conforme a los Términos de Apple Media Services y el <a href="https://www.apple.com/legal/internet-services/itunes/dev/stdeula/" target="_blank" rel="noopener">Acuerdo de licencia de usuario final (EULA) estándar de Apple</a>.`,
      term_h4:`4. Publicidad`,
      term_p4:`La versión gratuita muestra anuncios de Google AdMob. Al usar la versión gratuita, aceptas que se puedan mostrar anuncios. Comprar Premium elimina los anuncios.`,
      term_h5:`5. Suscripciones y compras`,
      term_l5:`<li><strong>Premium</strong> se ofrece como suscripción de renovación automática mensual o anual.</li><li>El pago se cobra a tu Apple ID al confirmar la compra.</li><li>Las suscripciones se renuevan automáticamente salvo que se cancelen al menos 24 horas antes de que termine el periodo actual.</li><li>Puedes gestionar o cancelar las suscripciones cuando quieras en los ajustes de tu Apple ID.</li><li>Todas las compras las procesa y gestiona Apple, sujetas a sus términos.</li><li>En Android, las compras las procesa y gestiona Google Play, sujetas a los términos de Google.</li>`,
      term_h6:`6. Uso aceptable`,
      term_p6:`Aceptas usar la app solo con fines legales y personales, y no hacer un mal uso, aplicar ingeniería inversa ni interferir con la app o su seguridad.`,
      term_h7:`7. Aviso de salud`,
      term_p7:`Study Sprint Timer es una herramienta de productividad y enfoque. No ofrece asesoramiento médico, psicológico ni profesional, y no debe usarse con ese fin.`,
      term_h8:`8. Renuncia de garantías`,
      term_p8:`La app se ofrece "tal cual" y "según disponibilidad", sin garantías de ningún tipo, en la máxima medida permitida por la ley. No garantizamos que sea ininterrumpida ni esté libre de errores.`,
      term_h9:`9. Limitación de responsabilidad`,
      term_p9:`En la máxima medida permitida por la ley, no somos responsables de daños indirectos, incidentales o consecuentes derivados del uso de la app.`,
      term_h10:`10. Cambios en estos términos`,
      term_p10:`Podemos actualizar estos Términos de vez en cuando. El uso continuado de la app tras los cambios constituye la aceptación de los Términos actualizados.`,
      term_h11:`11. Contacto`,
      term_p11:`¿Preguntas sobre estos Términos? Escríbenos a <a href="mailto:support@studysprinttimer.com">support@studysprinttimer.com</a>.`,
      ft_desc:`Enfoque, Pomodoro y rachas — un temporizador de estudio simple y sin conexión.`,
      ft_badge:`Disponible en la App Store`,
      ft_features:`Funciones`,
      ft_how:`Cómo funciona`,
      ft_reviews:`Opiniones`,
      ft_help:`Centro de ayuda`,
      ft_contact:`Contáctanos`,
      ft_privacy:`Política de privacidad`,
      ft_terms:`Términos del servicio`,
      ft_copy:`© 2026 Study Sprint Timer · Harun Doğdu`,
    },
    fr: {
      nav_home:`Accueil`,
      nav_privacy:`Confidentialité`,
      nav_terms:`Conditions`,
      nav_support:`Support`,
      nav_help:`Aide`,
      nav_contact:`Contact`,
      sup_hero_title:`Support et centre d'aide`,
      sup_hero_sub:`Nous sommes là pour vous aider à vous concentrer.`,
      sup_get_title:`Nous contacter`,
      sup_get_desc:`Besoin d'aide, un bug repéré ou une idée de fonctionnalité ? Nous serions ravis de vous lire.`,
      sup_get_btn:`Contacter le support`,
      sup_or_pre:`Ou écrivez-nous directement à`,
      sup_or_post:`. Nous répondons généralement sous quelques jours.`,
      sup_faq_title:`Questions fréquentes`,
      sup_q1:`L'application fonctionne-t-elle hors ligne ?`,
      sup_a1:`Oui. Study Sprint Timer fonctionne hors ligne — aucun compte ni connexion Internet n'est requis pour lancer des sessions et suivre votre progression.`,
      sup_q2:`Comment fonctionnent les séries ?`,
      sup_a2:`Terminez au moins une session d'étude dans la journée pour garder votre série. Si vous manquez un jour, elle se réinitialise — un petit coup de pouce pour rester régulier.`,
      sup_q3:`Comment changer le thème ?`,
      sup_a3:`Ouvrez Réglages → Thème et choisissez la couleur souhaitée. Sur les appareils compatibles, l'icône de l'app s'adapte à votre thème.`,
      sup_q4:`Comment retirer les publicités ?`,
      sup_a4:`Passez à Premium depuis l'app pour une expérience sans publicité et des thèmes supplémentaires.`,
      sup_q5:`Comment restaurer mon achat ?`,
      sup_a5:`Allez dans Réglages → Restaurer les achats. Connectez-vous avec le même identifiant Apple utilisé lors de l'achat.`,
      sup_q6:`Comment supprimer mes données ?`,
      sup_a6:`Toutes les données sont stockées localement. Vous pouvez tout effacer via Réglages → Effacer les données, ou en désinstallant l'app.`,
      sup_q7:`Y a-t-il une app Apple Watch ?`,
      sup_a7:`Oui. Installez l'app Watch pour lancer des sprints depuis votre poignet ; les sessions se synchronisent automatiquement avec votre iPhone.`,
      sup_q8:`Puis-je enregistrer mes sessions dans Apple Santé ?`,
      sup_a8:`Oui. Activez « Enregistrer dans Apple Santé » dans les Réglages ; les sessions terminées apparaissent dans Santé comme minutes de pleine conscience.`,
      priv_hero_title:`Politique de confidentialité`,
      priv_hero_sub:`Comment Study Sprint Timer traite vos données.`,
      priv_updated:`Dernière mise à jour : 3 septembre 2026`,
      priv_h1:`Aperçu`,
      priv_p1:`Study Sprint Timer (« l'app ») est un minuteur d'étude de concentration et Pomodoro hors ligne. Nous l'avons conçu dans le respect de votre vie privée. L'app ne nécessite aucun compte et ne demande ni nom, ni e-mail, ni donnée personnelle.`,
      priv_h2:`Informations que nous collectons`,
      priv_p2:`<strong>Vos données d'étude restent sur l'appareil.</strong> Les sessions, les livres, les séries et les objectifs sont stockés localement et ne nous parviennent jamais. Ce qui quitte l'appareil est décrit plus bas : mesure d'usage, rapports de plantage, et les données dont les fournisseurs de publicité et d'abonnement ont besoin.`,
      priv_h3:`Publicité et services tiers`,
      priv_p3:`La version gratuite affiche des publicités via <strong>Google AdMob</strong>. Pour diffuser et mesurer les publicités, Google peut collecter et traiter certaines informations, comme un identifiant publicitaire, l'adresse IP et des données d'usage générales. Ce traitement est effectué par Google, pas par nous.`,
      priv_l3:`<li>Nous utilisons la User Messaging Platform de Google pour recueillir votre consentement lorsque requis.</li><li>Sur iOS, nous affichons l'invite App Tracking Transparency d'Apple. Si vous refusez le suivi, l'app fonctionne pleinement et vous pouvez voir des publicités moins pertinentes.</li><li>En savoir plus dans la <a href="https://policies.google.com/privacy" target="_blank" rel="noopener">Politique de confidentialité de Google</a>.</li>`,
      priv_p3c:`Nous utilisons aussi <strong>Google Firebase</strong>. Il mesure quels écrans et quelles fonctions sont utilisés, nous envoie un rapport quand l'application plante, distribue les annonces que vous pouvez activer, et nous permet de modifier quelques réglages sans publier une mise à jour.`,
      priv_l3c:`<li>Rien de tout cela ne contient votre nom, votre adresse e-mail ou vos notes de révision.</li><li>Les rapports de plantage indiquent le modèle de l'appareil et la version d'iOS ou d'Android, pour que nous puissions reproduire le problème.</li><li>Vous pouvez désactiver les annonces dans les Réglages à tout moment.</li><li>Les détails sont sur <a href="https://firebase.google.com/support/privacy" target="_blank" rel="noopener">la page de confidentialité de Firebase</a>.</li>`,
      priv_p3b:`Acheter <strong>Premium</strong> supprime toutes les publicités.`,
      priv_h4:`Achats`,
      priv_p4:`Les abonnements et achats sont traités par <strong>Apple</strong> via l'App Store. Nous ne recevons ni ne stockons jamais vos informations de paiement. Pour vérifier si votre abonnement est actif et pour transporter votre code de synchronisation entre vos propres appareils, l'app utilise <strong>RevenueCat</strong>. RevenueCat reçoit les événements d'achat et un identifiant généré par l'app ; il ne reçoit jamais vos informations de paiement ni votre nom. Le traitement par Apple est régi par la <a href="https://www.apple.com/legal/privacy/" target="_blank" rel="noopener">Politique de confidentialité d'Apple</a> et la <a href="https://www.revenuecat.com/privacy" target="_blank" rel="noopener">politique de confidentialité de RevenueCat</a>.`,
      priv_h4b:`Apple Santé (facultatif)`,
      priv_p4b:`Si vous activez la synchronisation avec Apple Santé, l'app enregistre vos sessions de concentration terminées dans Apple Santé sous forme de minutes de pleine conscience. Seule la durée de la session est écrite ; l'app ne lit rien dans Santé. Vos données Santé restent sur votre appareil, protégées par Apple, et vous pouvez désactiver cette option à tout moment dans Réglages iOS → Santé.`,
      priv_h4c:`Recherche de livres (facultatif)`,
      priv_p4c:`Lorsque vous ajoutez un livre à votre bibliothèque, l'app peut en remplir les informations à votre place. Pendant que vous saisissez un titre, ce texte est envoyé à <strong>Open Library</strong> afin que l'app propose des titres, des auteurs et un nombre de pages ; les couvertures sont chargées depuis les serveurs d'Open Library. Cela ne se produit que pendant que vous écrivez dans le champ de recherche. Nous ne recevons ni ne conservons ces recherches, et vous pouvez ignorer les suggestions et tout saisir vous-même. Sans connexion Internet, la recherche ne renvoie rien et le reste de l'app continue de fonctionner. Open Library est géré par l'Internet Archive ; consultez leur <a href="https://archive.org/about/terms.php" target="_blank" rel="noopener">politique de confidentialité</a>.`,
      priv_h4d:`Calendrier Apple (facultatif)`,
      priv_p4d:`Si vous activez la synchronisation avec le calendrier, l'app inscrit chaque session terminée dans un calendrier distinct nommé "Study Sprint" au sein de votre app Calendrier. Elle ne fait qu'écrire des entrées : elle ne lit pas vos événements existants et ne modifie pas vos autres calendriers. Ces entrées restent dans votre propre compte de calendrier, nous ne les voyons donc jamais. Vous pouvez désactiver l'option dans les Réglages de l'app ou révoquer l'accès dans Réglages iOS → Confidentialité et sécurité → Calendriers.`,
      priv_h4e:`Bouclier de concentration (facultatif)`,
      priv_p4e:`Le bouclier de concentration garde fermées les apps que vous choisissez pendant une session. Il s'appuie sur Temps d'écran (Family Controls) d'Apple, qui demande votre autorisation au premier usage. Les apps choisies restent sur votre appareil sous forme de jetons que seul iOS peut lire ; la liste ne nous parvient jamais. Vous pouvez désactiver le bouclier dans les réglages de l'app ou retirer l'autorisation dans Réglages iOS → Temps d'écran.`,
      priv_h4f:`Game Center (facultatif)`,
      priv_p4f:`Si vous vous connectez à Game Center, l'app envoie deux chiffres aux classements : vos minutes de concentration de la semaine et votre plus longue série. Ils vont chez Apple, sous la politique de confidentialité d'Apple, et nous ne les voyons jamais. Rester déconnecté ne coûte que les classements et les succès ; tout le reste fonctionne pareil.`,
      priv_h4g:`La version Android`,
      priv_p4g:`Sur Android, les achats passent par Google Play plutôt que par Apple, et l'app contient Firebase Analytics, qui envoie des mesures d'utilisation à Google. Apple Santé, le Calendrier d'Apple, l'app Apple Watch et le bouclier de concentration sont des fonctions iPhone et n'ont pas d'équivalent sur Android. Le reste de cette politique vaut pour les deux versions : vos données d'étude restent sur votre appareil et nous n'exploitons aucun serveur.`,
      priv_h5:`Partage des données`,
      priv_p5:`Nous ne vendons, ne louons ni n'échangeons vos informations. Nous ne partageons vos données d'étude stockées localement avec personne.`,
      priv_h6:`Vos choix`,
      priv_l6:`<li>Gérez le suivi via Réglages iOS → Confidentialité et sécurité → Suivi.</li><li>Réinitialisez votre identifiant publicitaire dans les Réglages iOS.</li><li>Supprimez entièrement les publicités en achetant Premium.</li><li>Effacez toutes les données locales à tout moment via Réglages → Effacer les données, ou en désinstallant l'app.</li>`,
      priv_h7:`Confidentialité des enfants`,
      priv_p7:`L'app ne s'adresse pas aux enfants de moins de 13 ans et nous ne collectons pas sciemment de données personnelles d'enfants.`,
      priv_h8:`Modifications de cette politique`,
      priv_p8:`Nous pouvons mettre à jour cette politique de temps à autre. Les changements importants seront indiqués sur cette page avec une nouvelle date de « Dernière mise à jour ».`,
      priv_h_rights:`Vos droits`,
      priv_p_rights:`<strong>Responsable du traitement :</strong> Harun Doğdu, <a href="mailto:support@studysprinttimer.com">support@studysprinttimer.com</a>. En vertu du RGPD et de la loi turque n° 6698 (KVKK), vous pouvez demander quelles données vous concernant sont traitées, en demander la rectification ou l'effacement, vous opposer au traitement et retirer le consentement donné pour la publicité et la mesure. Les publicités, la mesure et la vérification de l'abonnement sont traitées sur les infrastructures de Google, RevenueCat et Apple, sur des serveurs hors de Türkiye et, pour les utilisateurs européens, hors de l'EEE. Vos données d'étude ne quittent jamais votre appareil. Nous répondons sous 30 jours.`,
      priv_h9:`Contact`,
      priv_p9:`Des questions sur cette Politique de confidentialité ? Contactez-nous à <a href="mailto:support@studysprinttimer.com">support@studysprinttimer.com</a>.`,
      term_hero_title:`Conditions d'utilisation`,
      term_hero_sub:`Les règles d'utilisation de Study Sprint Timer.`,
      term_updated:`Dernière mise à jour : 3 septembre 2026`,
      term_h1:`1. Acceptation des conditions`,
      term_p1:`En téléchargeant ou en utilisant Study Sprint Timer (« l'app »), vous acceptez ces Conditions d'utilisation. Si vous n'êtes pas d'accord, veuillez ne pas utiliser l'app.`,
      term_h2:`2. Le service`,
      term_p2:`Study Sprint Timer est un minuteur d'étude de concentration et Pomodoro hors ligne. Il vous aide à réaliser des sessions minutées, à suivre des séries et à rester motivé. L'app fonctionne sans compte et stocke vos données localement.`,
      term_h3:`3. Licence`,
      term_p3:`Nous vous accordons une licence personnelle, non transférable et non exclusive d'utilisation de l'app sur des appareils Apple que vous possédez ou contrôlez, conformément aux Conditions d'Apple Media Services et au <a href="https://www.apple.com/legal/internet-services/itunes/dev/stdeula/" target="_blank" rel="noopener">Contrat de licence utilisateur final (CLUF) standard d'Apple</a>.`,
      term_h4:`4. Publicité`,
      term_p4:`La version gratuite affiche des publicités fournies par Google AdMob. En utilisant la version gratuite, vous acceptez que des publicités puissent s'afficher. L'achat de Premium supprime les publicités.`,
      term_h5:`5. Abonnements et achats`,
      term_l5:`<li><strong>Premium</strong> est proposé sous forme d'abonnement à renouvellement automatique, mensuel ou annuel.</li><li>Le paiement est débité de votre identifiant Apple à la confirmation de l'achat.</li><li>Les abonnements se renouvellent automatiquement sauf annulation au moins 24 heures avant la fin de la période en cours.</li><li>Vous pouvez gérer ou annuler vos abonnements à tout moment dans les réglages de votre identifiant Apple.</li><li>Tous les achats sont traités et gérés par Apple, selon ses conditions.</li><li>Sur Android, les achats sont traités et gérés par Google Play, selon les conditions de Google.</li>`,
      term_h6:`6. Utilisation acceptable`,
      term_p6:`Vous acceptez d'utiliser l'app uniquement à des fins légales et personnelles, et de ne pas en abuser, la désosser ou perturber l'app ou sa sécurité.`,
      term_h7:`7. Avertissement santé`,
      term_p7:`Study Sprint Timer est un outil de productivité et de concentration. Il ne fournit aucun conseil médical, psychologique ou professionnel et ne doit pas être utilisé à cette fin.`,
      term_h8:`8. Exclusion de garanties`,
      term_p8:`L'app est fournie « telle quelle » et « selon disponibilité », sans garantie d'aucune sorte, dans la mesure maximale permise par la loi. Nous ne garantissons pas un fonctionnement ininterrompu ou sans erreur.`,
      term_h9:`9. Limitation de responsabilité`,
      term_p9:`Dans la mesure maximale permise par la loi, nous ne sommes pas responsables des dommages indirects, accessoires ou consécutifs découlant de votre utilisation de l'app.`,
      term_h10:`10. Modifications de ces conditions`,
      term_p10:`Nous pouvons mettre à jour ces Conditions de temps à autre. L'utilisation continue de l'app après modifications vaut acceptation des Conditions mises à jour.`,
      term_h11:`11. Contact`,
      term_p11:`Des questions sur ces Conditions ? Contactez-nous à <a href="mailto:support@studysprinttimer.com">support@studysprinttimer.com</a>.`,
      ft_desc:`Concentration, Pomodoro & séries — un minuteur d'étude simple et hors ligne.`,
      ft_badge:`Disponible sur l'App Store`,
      ft_features:`Fonctionnalités`,
      ft_how:`Comment ça marche`,
      ft_reviews:`Avis`,
      ft_help:`Centre d'aide`,
      ft_contact:`Nous contacter`,
      ft_privacy:`Politique de confidentialité`,
      ft_terms:`Conditions d'utilisation`,
      ft_copy:`© 2026 Study Sprint Timer · Harun Doğdu`,
    },
    ru: {
      nav_home:`Главная`,
      nav_privacy:`Конфиденциальность`,
      nav_terms:`Условия`,
      nav_support:`Поддержка`,
      nav_help:`Помощь`,
      nav_contact:`Связаться`,
      sup_hero_title:`Поддержка и центр помощи`,
      sup_hero_sub:`Мы здесь, чтобы помочь вам сосредоточиться.`,
      sup_get_title:`Свяжитесь с нами`,
      sup_get_desc:`Нужна помощь, нашли ошибку или есть идея? Будем рады вашему сообщению.`,
      sup_get_btn:`Написать в поддержку`,
      sup_or_pre:`Или напишите нам напрямую на`,
      sup_or_post:`. Обычно отвечаем в течение нескольких дней.`,
      sup_faq_title:`Частые вопросы`,
      sup_q1:`Работает ли приложение офлайн?`,
      sup_a1:`Да. Study Sprint Timer работает офлайн — для учебных сессий и отслеживания прогресса не нужны аккаунт или интернет.`,
      sup_q2:`Как работают серии?`,
      sup_a2:`Завершите хотя бы одну учебную сессию за день, чтобы сохранить серию. Пропустите день — и она сбросится, мягко напоминая быть последовательным.`,
      sup_q3:`Как сменить тему?`,
      sup_a3:`Откройте Настройки → Тема и выберите любой цвет. На поддерживаемых устройствах иконка приложения меняется в тон вашей теме.`,
      sup_q4:`Как убрать рекламу?`,
      sup_a4:`Перейдите на Premium в приложении, чтобы избавиться от рекламы и открыть дополнительные темы.`,
      sup_q5:`Как восстановить покупку?`,
      sup_a5:`Откройте Настройки → Восстановить покупки. Убедитесь, что вошли с тем же Apple ID, что и при покупке.`,
      sup_q6:`Как удалить мои данные?`,
      sup_a6:`Все данные хранятся локально. Вы можете очистить всё в Настройки → Очистить данные или удалив приложение.`,
      sup_q7:`Есть ли приложение для Apple Watch?`,
      sup_a7:`Да. Установите приложение для Watch и запускайте спринты с запястья; сессии автоматически синхронизируются с iPhone.`,
      sup_q8:`Можно ли сохранять сессии в Apple Здоровье?`,
      sup_a8:`Да. Включите «Запись в Apple Здоровье» в настройках; завершённые сессии появятся в Здоровье как минуты осознанности.`,
      priv_hero_title:`Политика конфиденциальности`,
      priv_hero_sub:`Как Study Sprint Timer обрабатывает ваши данные.`,
      priv_updated:`Последнее обновление: 3 сентября 2026 г.`,
      priv_h1:`Обзор`,
      priv_p1:`Study Sprint Timer («приложение») — это офлайн-таймер для фокуса и учёбы по методу Pomodoro. Мы создали его с уважением к вашей приватности. Приложению не нужен аккаунт, и оно не запрашивает ваше имя, e-mail или любые персональные данные.`,
      priv_h2:`Какие данные мы собираем`,
      priv_p2:`<strong>Ваши учебные данные остаются на устройстве.</strong> Занятия, книги, серии и цели хранятся только там и до нас не доходят. Что уходит с устройства, описано ниже: измерение использования, отчёты о сбоях и данные, которые нужны рекламной и подписочной службам.`,
      priv_h3:`Реклама и сторонние сервисы`,
      priv_p3:`Бесплатная версия показывает рекламу через <strong>Google AdMob</strong>. Для показа и измерения рекламы Google может собирать и обрабатывать некоторые данные, например рекламный идентификатор, IP-адрес и общие данные об использовании. Эту обработку выполняет Google, а не мы.`,
      priv_l3:`<li>Мы используем Google User Messaging Platform, чтобы запросить ваше согласие там, где это необходимо.</li><li>На iOS мы показываем запрос App Tracking Transparency от Apple. Если вы откажетесь от отслеживания, приложение продолжит работать полностью, а реклама может стать менее релевантной.</li><li>Подробнее в <a href="https://policies.google.com/privacy" target="_blank" rel="noopener">Политике конфиденциальности Google</a>.</li>`,
      priv_p3c:`Мы также используем <strong>Google Firebase</strong>. Он измеряет, какие экраны и функции открывают, присылает нам отчёт при сбое приложения, доставляет объявления, которые вы можете включить, и позволяет менять некоторые настройки без выпуска обновления.`,
      priv_l3c:`<li>Ничего из этого не содержит вашего имени, адреса почты или учебных заметок.</li><li>В отчёте о сбое есть модель устройства и версия iOS или Android — это нужно, чтобы воспроизвести ошибку.</li><li>Объявления можно отключить в настройках в любой момент.</li><li>Подробности — на <a href="https://firebase.google.com/support/privacy" target="_blank" rel="noopener">странице конфиденциальности Firebase</a>.</li>`,
      priv_p3b:`Покупка <strong>Premium</strong> убирает всю рекламу.`,
      priv_h4:`Покупки`,
      priv_p4:`Подписки и покупки обрабатывает <strong>Apple</strong> через App Store. Мы никогда не получаем и не храним ваши платёжные данные. Чтобы проверить, активна ли подписка, и чтобы перенести код синхронизации между вашими устройствами, приложение использует <strong>RevenueCat</strong>. RevenueCat получает события покупки и идентификатор, созданный приложением; платёжные данные и имя ему не передаются. Обработка со стороны Apple регулируется <a href="https://www.apple.com/legal/privacy/" target="_blank" rel="noopener">Политикой конфиденциальности Apple</a> и <a href="https://www.revenuecat.com/privacy" target="_blank" rel="noopener">политику конфиденциальности RevenueCat</a>.`,
      priv_h4b:`Apple Здоровье (по желанию)`,
      priv_p4b:`Если включить синхронизацию с Apple Здоровье, приложение записывает завершённые фокус-сессии в Apple Здоровье как минуты осознанности. Записывается только длительность сессии; приложение ничего не читает из Здоровья. Данные Здоровья остаются на вашем устройстве под защитой Apple, и вы можете отключить это в любой момент в Настройках iOS → Здоровье.`,
      priv_h4c:`Поиск книг (по желанию)`,
      priv_p4c:`Когда вы добавляете книгу в библиотеку, приложение может заполнить её данные за вас. Пока вы вводите название, этот текст отправляется в <strong>Open Library</strong>, чтобы приложение предложило подходящие названия, авторов и число страниц; обложки загружаются с серверов Open Library. Это происходит только в тот момент, когда вы печатаете в поле поиска. Мы не получаем и не храним эти запросы, а подсказки можно не использовать и ввести всё вручную. Без интернета поиск ничего не возвращает, а остальная часть приложения работает как обычно. Open Library поддерживает Internet Archive; см. их <a href="https://archive.org/about/terms.php" target="_blank" rel="noopener">политику конфиденциальности</a>.`,
      priv_h4d:`Календарь Apple (по желанию)`,
      priv_p4d:`Если включить синхронизацию с календарём, приложение записывает каждую завершённую сессию в отдельный календарь "Study Sprint" в вашем приложении Календарь. Оно только добавляет записи: существующие события не читаются, другие календари не изменяются. Записи остаются в вашей собственной учётной записи календаря, поэтому мы их никогда не видим. Отключить эту опцию можно в Настройках приложения, а доступ отозвать в Настройках iOS → Конфиденциальность и безопасность → Календари.`,
      priv_h4e:`Щит фокуса (по желанию)`,
      priv_p4e:`Щит фокуса держит выбранные вами приложения закрытыми, пока идёт сессия. Он работает через «Экранное время» (Family Controls) Apple и при первом включении спрашивает разрешение. Выбранные приложения хранятся на устройстве в виде токенов, которые читает только iOS, поэтому список к нам не попадает. Щит выключается в настройках приложения, а разрешение отзывается в Настройках iOS → Экранное время.`,
      priv_h4f:`Game Center (по желанию)`,
      priv_p4f:`Если вы вошли в Game Center, приложение отправляет в таблицы лидеров два числа: минуты фокуса за неделю и самую длинную серию. Они уходят к Apple и подчиняются политике конфиденциальности Apple; мы их не видим. Если не входить, вы теряете только таблицы лидеров и достижения, всё остальное работает так же.`,
      priv_h4g:`Версия для Android`,
      priv_p4g:`На Android покупки проходят через Google Play, а не через Apple, и в приложении есть Firebase Analytics, который отправляет измерения использования в Google. Apple Health, Календарь Apple, приложение для Apple Watch и щит фокуса — функции iPhone, на Android их нет. Остальная часть этой политики верна для обеих версий: данные о занятиях остаются на вашем устройстве, и своего сервера у нас нет.`,
      priv_h5:`Передача данных`,
      priv_p5:`Мы не продаём, не сдаём в аренду и не обмениваем вашу информацию. Мы не передаём никому ваши локально хранимые учебные данные.`,
      priv_h6:`Ваш выбор`,
      priv_l6:`<li>Управляйте отслеживанием в Настройки iOS → Конфиденциальность и безопасность → Отслеживание.</li><li>Сбросьте рекламный идентификатор в настройках iOS.</li><li>Полностью уберите рекламу, купив Premium.</li><li>Удалите все локальные данные в любой момент через Настройки → Очистить данные или удалив приложение.</li>`,
      priv_h7:`Конфиденциальность детей`,
      priv_p7:`Приложение не предназначено для детей младше 13 лет, и мы сознательно не собираем персональные данные детей.`,
      priv_h8:`Изменения этой политики`,
      priv_p8:`Мы можем время от времени обновлять эту политику. Существенные изменения будут отражены на этой странице с новой датой «Обновлено».`,
      priv_h_rights:`Ваши права`,
      priv_p_rights:`<strong>Оператор данных:</strong> Harun Doğdu, <a href="mailto:support@studysprinttimer.com">support@studysprinttimer.com</a>. По GDPR и турецкому закону № 6698 (KVKK) вы можете запросить, какие данные о вас обрабатываются, потребовать их исправления или удаления, возразить против обработки и отозвать согласие, данное на рекламу и аналитику. Реклама, аналитика и проверка подписки обрабатываются в инфраструктуре Google, RevenueCat и Apple, на серверах за пределами Турции, а для пользователей из Европы и за пределами ЕЭЗ. Данные ваших занятий никогда не покидают устройство. Мы отвечаем в течение 30 дней.`,
      priv_h9:`Контакты`,
      priv_p9:`Вопросы по этой Политике конфиденциальности? Напишите нам на <a href="mailto:support@studysprinttimer.com">support@studysprinttimer.com</a>.`,
      term_hero_title:`Условия использования`,
      term_hero_sub:`Правила использования Study Sprint Timer.`,
      term_updated:`Последнее обновление: 3 сентября 2026 г.`,
      term_h1:`1. Принятие условий`,
      term_p1:`Загружая или используя Study Sprint Timer («приложение»), вы соглашаетесь с этими Условиями использования. Если вы не согласны, пожалуйста, не используйте приложение.`,
      term_h2:`2. Сервис`,
      term_p2:`Study Sprint Timer — это офлайн-таймер для фокуса и учёбы по методу Pomodoro. Он помогает проводить сессии по таймеру, отслеживать серии и оставаться мотивированным. Приложение работает без аккаунта и хранит данные локально.`,
      term_h3:`3. Лицензия`,
      term_p3:`Мы предоставляем вам личную, непередаваемую, неисключительную лицензию на использование приложения на устройствах Apple, которыми вы владеете или управляете, в соответствии с Условиями Apple Media Services и стандартным <a href="https://www.apple.com/legal/internet-services/itunes/dev/stdeula/" target="_blank" rel="noopener">Лицензионным соглашением Apple (EULA)</a>.`,
      term_h4:`4. Реклама`,
      term_p4:`Бесплатная версия показывает рекламу от Google AdMob. Используя бесплатную версию, вы соглашаетесь на показ рекламы. Покупка Premium убирает рекламу.`,
      term_h5:`5. Подписки и покупки`,
      term_l5:`<li><strong>Premium</strong> доступен как ежемесячная или годовая автоматически продлеваемая подписка.</li><li>Оплата списывается с вашего Apple ID при подтверждении покупки.</li><li>Подписки продлеваются автоматически, если не отменены не позднее чем за 24 часа до конца текущего периода.</li><li>Вы можете управлять подписками или отменить их в любой момент в настройках Apple ID.</li><li>Все покупки обрабатываются и управляются Apple в соответствии с её условиями.</li><li>На Android покупки обрабатывает и ведёт Google Play в соответствии с условиями Google.</li>`,
      term_h6:`6. Допустимое использование`,
      term_p6:`Вы соглашаетесь использовать приложение только в законных личных целях и не злоупотреблять им, не подвергать обратной разработке и не вмешиваться в его работу или безопасность.`,
      term_h7:`7. Отказ по вопросам здоровья`,
      term_p7:`Study Sprint Timer — инструмент продуктивности и фокуса. Он не даёт медицинских, психологических или профессиональных советов, и на него нельзя полагаться в таких целях.`,
      term_h8:`8. Отказ от гарантий`,
      term_p8:`Приложение предоставляется «как есть» и «как доступно», без каких-либо гарантий, в максимально разрешённой законом степени. Мы не гарантируем бесперебойную или безошибочную работу.`,
      term_h9:`9. Ограничение ответственности`,
      term_p9:`В максимально разрешённой законом степени мы не несём ответственности за косвенные, случайные или последующие убытки, возникшие в результате использования приложения.`,
      term_h10:`10. Изменения этих условий`,
      term_p10:`Мы можем время от времени обновлять эти Условия. Продолжение использования приложения после изменений означает принятие обновлённых Условий.`,
      term_h11:`11. Контакты`,
      term_p11:`Вопросы по этим Условиям? Напишите нам на <a href="mailto:support@studysprinttimer.com">support@studysprinttimer.com</a>.`,
      ft_desc:`Фокус, Pomodoro и серии — простой офлайн-таймер для учёбы.`,
      ft_badge:`В App Store`,
      ft_features:`Функции`,
      ft_how:`Как это работает`,
      ft_reviews:`Отзывы`,
      ft_help:`Центр помощи`,
      ft_contact:`Связаться`,
      ft_privacy:`Политика конфиденциальности`,
      ft_terms:`Условия использования`,
      ft_copy:`© 2026 Study Sprint Timer · Harun Doğdu`,
    },
    pt: {
      nav_home:`Início`,
      nav_privacy:`Privacidade`,
      nav_terms:`Termos`,
      nav_support:`Suporte`,
      nav_help:`Obter ajuda`,
      nav_contact:`Contato`,
      sup_hero_title:`Central de suporte e ajuda`,
      sup_hero_sub:`Estamos aqui para ajudar você a se concentrar.`,
      sup_get_title:`Fale com a gente`,
      sup_get_desc:`Precisa de ajuda, encontrou um erro ou tem uma ideia? Queremos saber.`,
      sup_get_btn:`Falar com o suporte`,
      sup_or_pre:`Ou escreva direto para`,
      sup_or_post:`. Costumamos responder em alguns dias.`,
      sup_faq_title:`Perguntas frequentes`,
      sup_q1:`O app funciona sem internet?`,
      sup_a1:`Sim. O Study Sprint Timer foi feito para funcionar offline: você não precisa de conta nem de conexão para fazer suas sessões de estudo e acompanhar seu progresso.`,
      sup_q2:`Como funcionam as sequências?`,
      sup_a2:`Faça pelo menos uma sessão de estudo por dia para manter a sequência. Se pular um dia, ela recomeça do zero, como um empurrãozinho para você não perder o ritmo.`,
      sup_q3:`Como mudo o tema?`,
      sup_a3:`Abra Ajustes → Tema e escolha a cor que quiser. Em aparelhos compatíveis, o ícone do app na tela de início muda junto.`,
      sup_q4:`Como removo os anúncios?`,
      sup_a4:`Assine o Premium dentro do app para usar sem anúncios e liberar temas extras.`,
      sup_q5:`Como restauro minha compra?`,
      sup_a5:`Vá em Ajustes → Restaurar compras. Confira se você entrou com o mesmo ID Apple usado na compra.`,
      sup_q6:`Como apago meus dados?`,
      sup_a6:`Tudo fica guardado no seu aparelho. Você pode apagar em Ajustes → Limpar dados ou desinstalando o app.`,
      sup_q7:`Existe app para Apple Watch?`,
      sup_a7:`Sim. Instale o app do Watch para começar sprints direto do pulso; as sessões voltam para o iPhone sozinhas.`,
      sup_q8:`Dá para salvar as sessões no Apple Health?`,
      sup_a8:`Sim. Ative "Gravar no Apple Health" nos Ajustes; as sessões concluídas aparecem no Health como Minutos de Atenção Plena.`,
      priv_hero_title:`Política de Privacidade`,
      priv_hero_sub:`Como o Study Sprint Timer lida com seus dados.`,
      priv_updated:`Última atualização: 3 de setembro de 2026`,
      priv_h1:`Visão geral`,
      priv_p1:`O Study Sprint Timer ("o app") é um cronômetro de foco e Pomodoro que funciona offline. Nós o construímos respeitando sua privacidade. O app não exige conta e não pede seu nome, e-mail ou qualquer dado pessoal para funcionar.`,
      priv_h2:`Informações que coletamos`,
      priv_p2:`<strong>Seus dados de estudo ficam no seu aparelho.</strong> As sessões, os livros, as sequências e as metas são guardados só ali, e nunca chegam até nós. O que sai do aparelho está descrito abaixo: medição de uso, relatórios de falha e os dados de que os serviços de anúncios e assinatura precisam.`,
      priv_h3:`Publicidade e serviços de terceiros`,
      priv_p3:`A versão gratuita do app exibe anúncios por meio do <strong>Google AdMob</strong>. Para entregar e medir os anúncios, o Google pode coletar e processar algumas informações, como o identificador de publicidade do aparelho, o endereço IP e dados gerais de uso. Esse processamento é feito pelo Google, não por nós.`,
      priv_l3:`<li>Usamos a User Messaging Platform do Google para pedir seu consentimento quando necessário.</li><li>No iOS, mostramos o aviso de Transparência no Rastreamento de Apps da Apple. Se você não permitir o rastreamento, o app continua funcionando por inteiro e você pode ver anúncios menos relevantes.</li><li>Saiba mais na <a href="https://policies.google.com/privacy" target="_blank" rel="noopener">Política de Privacidade do Google</a>.</li>`,
      priv_p3c:`Também usamos o <strong>Google Firebase</strong>. Ele mede quais telas e recursos são usados, nos envia um relatório quando o app trava, entrega os avisos que você pode ativar e nos permite mudar alguns ajustes sem publicar uma atualização.`,
      priv_l3c:`<li>Nada disso leva seu nome, seu e-mail ou suas anotações de estudo.</li><li>Os relatórios de falha trazem o modelo do aparelho e a versão do iOS ou do Android, para conseguirmos reproduzir o erro.</li><li>Você pode desativar os avisos em Ajustes quando quiser.</li><li>Os detalhes estão na <a href="https://firebase.google.com/support/privacy" target="_blank" rel="noopener">página de privacidade do Firebase</a>.</li>`,
      priv_p3b:`Assinar o <strong>Premium</strong> remove todos os anúncios.`,
      priv_h4:`Compras`,
      priv_p4:`As assinaturas e compras são processadas pela <strong>Apple</strong> através da App Store. Nunca recebemos nem guardamos seus dados de pagamento. Para verificar se sua assinatura está ativa e para levar seu código de sincronização entre seus próprios aparelhos, o app usa a <strong>RevenueCat</strong>. A RevenueCat recebe os eventos de compra e um identificador gerado pelo app; ela nunca recebe seus dados de pagamento nem seu nome. O tratamento pela Apple segue a <a href="https://www.apple.com/legal/privacy/" target="_blank" rel="noopener">Política de Privacidade da Apple</a> e a <a href="https://www.revenuecat.com/privacy" target="_blank" rel="noopener">política de privacidade da RevenueCat</a>.`,
      priv_h4b:`Apple Health (opcional)`,
      priv_p4b:`Se você ativar a sincronização com o Apple Health, o app grava suas sessões de foco concluídas no Apple Health como Minutos de Atenção Plena. Ele grava só a duração da sessão e não lê nada do Health. Seus dados do Health ficam no seu aparelho, sob as proteções de privacidade da Apple, e você pode desligar isso quando quiser em Ajustes do iOS → Saúde.`,
      priv_h4c:`Busca de livros (opcional)`,
      priv_p4c:`Quando você adiciona um livro à sua estante, o app pode preencher os dados para você. Enquanto você digita um título, esse texto é enviado para a <strong>Open Library</strong> para o app sugerir títulos, autores e número de páginas; as capas são carregadas dos servidores da Open Library. Isso acontece só enquanto você digita no campo de busca. Não recebemos nem guardamos essas buscas, e você pode ignorar as sugestões e digitar tudo à mão. Sem internet a busca não retorna nada e o resto do app continua funcionando. A Open Library é mantida pelo Internet Archive; veja a <a href="https://archive.org/about/terms.php" target="_blank" rel="noopener">política de privacidade</a> deles.`,
      priv_h4d:`Calendário da Apple (opcional)`,
      priv_p4d:`Se você ativar a sincronização com o calendário, o app grava cada sessão concluída num calendário separado chamado "Study Sprint" no seu app Calendário. Ele só grava entradas: não lê seus eventos existentes e não mexe nos seus outros calendários. Essas entradas ficam na sua própria conta de calendário, então nunca as vemos. Você pode desligar a opção nos Ajustes do app ou retirar o acesso em Ajustes do iOS → Privacidade e Segurança → Calendários.`,
      priv_h4e:`Escudo de foco (opcional)`,
      priv_p4e:`O Escudo de foco mantém fechados os apps que você escolher enquanto uma sessão corre. Ele usa o Tempo de Uso (Family Controls) da Apple, que pede sua permissão na primeira vez que você liga. Os apps escolhidos ficam no seu aparelho como identificadores que só o iOS consegue ler, então a lista nunca chega até nós. Desligue o escudo nos Ajustes do app ou retire a permissão em Ajustes do iOS → Tempo de Uso.`,
      priv_h4f:`Game Center (opcional)`,
      priv_p4f:`Se você entrar no Game Center, o app envia dois números para o ranking: seus minutos de foco da semana e sua maior sequência. Eles vão para a Apple sob a política de privacidade da Apple, e nós nunca os vemos. Ficar de fora custa só o ranking e as conquistas; todo o resto funciona igual.`,
      priv_h4g:`A versão Android`,
      priv_p4g:`No Android as compras passam pelo Google Play em vez da Apple, e o app inclui o Firebase Analytics, que envia medições de uso ao Google. Apple Health, Calendário da Apple, o app do Apple Watch e o Escudo de foco são recursos do iPhone e não têm equivalente no Android. O resto desta política vale para as duas versões: seus dados de estudo ficam no seu aparelho e não mantemos servidor nenhum.`,
      priv_h5:`Compartilhamento de dados`,
      priv_p5:`Não vendemos, alugamos nem trocamos suas informações. Não compartilhamos com ninguém os dados de estudo guardados no seu aparelho.`,
      priv_h6:`Suas escolhas`,
      priv_l6:`<li>Gerencie o rastreamento em Ajustes do iOS → Privacidade e Segurança → Rastreamento.</li><li>Redefina seu identificador de publicidade nos Ajustes do iOS.</li><li>Remova os anúncios de vez assinando o Premium.</li><li>Apague todos os dados locais quando quiser em Ajustes → Limpar dados, ou desinstalando o app.</li>`,
      priv_h7:`Privacidade de crianças`,
      priv_p7:`O app não é destinado a menores de 13 anos e não coletamos intencionalmente dados pessoais de crianças.`,
      priv_h8:`Mudanças nesta política`,
      priv_p8:`Podemos atualizar esta política de tempos em tempos. Mudanças relevantes aparecerão nesta página com uma nova data de "Última atualização".`,
      priv_h_rights:`Seus direitos`,
      priv_p_rights:`<strong>Controlador dos dados:</strong> Harun Doğdu, <a href="mailto:support@studysprinttimer.com">support@studysprinttimer.com</a>. Pelo GDPR e pela lei turca nº 6698 (KVKK), você pode perguntar quais dados seus são tratados, pedir correção ou exclusão, se opor ao tratamento e retirar o consentimento dado para anúncios e medição. Os anúncios, a medição e a verificação de assinatura rodam na infraestrutura do Google, da RevenueCat e da Apple, em servidores fora da Turquia e, para usuários na Europa, fora do EEE. Seus dados de estudo em si nunca saem do seu aparelho. Respondemos aos pedidos em até 30 dias.`,
      priv_h9:`Contato`,
      priv_p9:`Dúvidas sobre esta Política de Privacidade? Fale com a gente em <a href="mailto:support@studysprinttimer.com">support@studysprinttimer.com</a>.`,
      term_hero_title:`Termos de Serviço`,
      term_hero_sub:`As regras para usar o Study Sprint Timer.`,
      term_updated:`Última atualização: 3 de setembro de 2026`,
      term_h1:`1. Aceitação dos termos`,
      term_p1:`Ao baixar ou usar o Study Sprint Timer ("o app"), você concorda com estes Termos de Serviço. Se não concordar, não use o app.`,
      term_h2:`2. O serviço`,
      term_p2:`O Study Sprint Timer é um cronômetro de foco e Pomodoro que funciona offline. Ele ajuda você a fazer sessões de estudo cronometradas, acompanhar sequências e manter a motivação. O app funciona sem conta e guarda seus dados no próprio aparelho.`,
      term_h3:`3. Licença`,
      term_p3:`Concedemos a você uma licença pessoal, intransferível e não exclusiva para usar o app em aparelhos Apple que você possua ou controle, de acordo com os Termos dos Serviços de Mídia da Apple e o <a href="https://www.apple.com/legal/internet-services/itunes/dev/stdeula/" target="_blank" rel="noopener">Contrato de Licença de Usuário Final (EULA) padrão da Apple</a>.`,
      term_h4:`4. Publicidade`,
      term_p4:`A versão gratuita do app exibe anúncios fornecidos pelo Google AdMob. Ao usar a versão gratuita, você concorda que anúncios podem ser exibidos. Assinar o Premium remove os anúncios.`,
      term_h5:`5. Assinaturas e compras`,
      term_l5:`<li>O <strong>Premium</strong> é oferecido como assinatura de renovação automática mensal ou anual.</li><li>A cobrança é feita no seu Apple ID ao confirmar a compra.</li><li>As assinaturas renovam sozinhas, a menos que sejam canceladas pelo menos 24 horas antes do fim do período atual.</li><li>Você pode gerenciar ou cancelar a assinatura quando quiser nos ajustes da sua conta Apple ID.</li><li>Todas as compras são processadas e gerenciadas pela Apple, sujeitas aos termos da Apple.</li><li>No Android, as compras são processadas e gerenciadas pelo Google Play, sujeitas aos termos do Google.</li>`,
      term_h6:`6. Uso aceitável`,
      term_p6:`Você concorda em usar o app apenas para fins pessoais e lícitos, sem fazer mau uso, aplicar engenharia reversa ou interferir no app ou na sua segurança.`,
      term_h7:`7. Aviso sobre saúde`,
      term_p7:`O Study Sprint Timer é uma ferramenta de produtividade e foco. Ele não oferece orientação médica, psicológica ou profissional, e não deve ser usado com esse fim.`,
      term_h8:`8. Isenção de garantias`,
      term_p8:`O app é fornecido "no estado em que se encontra" e "conforme disponível", sem garantias de nenhum tipo, na máxima extensão permitida por lei. Não garantimos que o app funcionará sem interrupções ou sem erros.`,
      term_h9:`9. Limitação de responsabilidade`,
      term_p9:`Na máxima extensão permitida por lei, não somos responsáveis por danos indiretos, incidentais ou consequentes decorrentes do uso do app.`,
      term_h10:`10. Mudanças nestes termos`,
      term_p10:`Podemos atualizar estes Termos de tempos em tempos. Continuar usando o app depois das mudanças significa que você aceita os Termos atualizados.`,
      term_h11:`11. Contato`,
      term_p11:`Dúvidas sobre estes Termos? Fale com a gente em <a href="mailto:support@studysprinttimer.com">support@studysprinttimer.com</a>.`,
      ft_desc:`Foco, Pomodoro e sequências: um cronômetro de estudos simples e offline.`,
      ft_badge:`Disponível na App Store`,
      ft_features:`Recursos`,
      ft_how:`Como funciona`,
      ft_reviews:`Avaliações`,
      ft_help:`Central de ajuda`,
      ft_contact:`Fale conosco`,
      ft_privacy:`Política de Privacidade`,
      ft_terms:`Termos de Serviço`,
      ft_copy:`© 2026 Study Sprint Timer · Harun Doğdu`,
    }
  };

  function applyLang(l) {
    var d = I18N[l] || I18N.en;
    document.querySelectorAll('[data-i18n]').forEach(function (el) {
      var k = el.getAttribute('data-i18n');
      if (d[k] != null) el.innerHTML = d[k];
    });
    document.documentElement.lang = l;
    var code = document.getElementById('langCode');
    if (code) code.textContent = l.toUpperCase();
    document.querySelectorAll('.lang-menu button').forEach(function (b) {
      b.classList.toggle('active', b.getAttribute('data-lang') === l);
    });
    try { localStorage.setItem('sst_lang', l); } catch (e) {}
  }

  var saved = null; try { saved = localStorage.getItem('sst_lang'); } catch (e) {}
  var navL = (navigator.language || 'en').slice(0, 2).toLowerCase();
  var init = I18N[saved] ? saved : (I18N[navL] ? navL : 'en');

  var lang = document.getElementById('lang');
  if (lang) {
    var btn = lang.querySelector('.lang-btn');
    btn.addEventListener('click', function (e) { e.stopPropagation(); lang.classList.toggle('open'); });
    document.addEventListener('click', function () { lang.classList.remove('open'); });
    lang.querySelectorAll('.lang-menu button').forEach(function (b) {
      b.addEventListener('click', function () { applyLang(b.getAttribute('data-lang')); lang.classList.remove('open'); });
    });
  }
  applyLang(init);

  var toggle = document.getElementById('themeToggle');
  if (toggle) toggle.addEventListener('click', function () {
    var cur = document.documentElement.getAttribute('data-theme') === 'dark' ? 'dark' : 'light';
    var next = cur === 'dark' ? 'light' : 'dark';
    document.documentElement.setAttribute('data-theme', next);
    try { localStorage.setItem('sst_theme', next); } catch (e) {}
  });
})();
